### ISSUE TITLE
Trying to create Windows nodegroup with 1.15 causes SIGSEGV

### ISSUE THREAD

**Issue by jairenee** [weaveworks/eksctl#1944]
**What happened?**
A description of actual behavior (with error messages).

I am trying to create a Windows nodegroup. I followed the instructions on the official documentation: https://docs.aws.amazon.com/eks/latest/userguide/launch-windows-workers.html

I ran this command:

$ eksctl create nodegroup --cluster training --profile mfa --region us-east-1 --name windows -m 1 -M 3 -N 2 --node-ami-family WindowsServer2019FullContainer --node-type m5.large

And got this error:

[ℹ]  eksctl version 0.15.0
[ℹ]  using region us-east-1
[ℹ]  1 nodegroup(s) that already exist (ng-b392aa65) will be excluded
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1844eb0]

goroutine 1 [running]:
github.com/weaveworks/eksctl/pkg/ami.Use(0x33eabc0, 0xc00000ea88, 0xc0003242c0, 0x7ffc460ed7bc, 0x4)
	github.com/weaveworks/eksctl@/pkg/ami/api.go:57 +0x160
github.com/weaveworks/eksctl/pkg/eks.EnsureAMI(0x33ad7e0, 0xc0004d7220, 0x7ffc460ed7bc, 0x4, 0xc0003242c0, 0x0, 0x0)
	github.com/weaveworks/eksctl@/pkg/eks/api.go:301 +0x361
github.com/weaveworks/eksctl/pkg/ctl/create.doCreateNodeGroups(0xc00029e280, 0xc0003242c0, 0x1, 0x0, 0x0)
	github.com/weaveworks/eksctl@/pkg/ctl/create/nodegroup.go:127 +0x3db
github.com/weaveworks/eksctl/pkg/ctl/create.createNodeGroupCmd.func1(0xc00030ca00, 0xc00025a3c0, 0x0, 0x14, 0x0, 0x0)
	github.com/weaveworks/eksctl@/pkg/ctl/create/nodegroup.go:40 +0xa5
github.com/spf13/cobra.(*Command).execute(0xc00030ca00, 0xc00025a280, 0x14, 0x14, 0xc00030ca00, 0xc00025a280)
	github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc00030c280, 0xc0002b1c20, 0x1, 0x1)
	github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
	github.com/weaveworks/eksctl@/cmd/eksctl/main.go:79 +0x407

When I added --version 1.14, everything created successfully, but using 1.15 does not work at all.

To reproduce, all I did was run the "install-vpc-controllers" command from the documentation above and then the command. The cluster itself was default.

**Anything else we need to know?**
What OS are you using, are you using a downloaded binary or did you compile eksctl, what type of AWS credentials are you using (i.e. default/named profile, MFA) - please don't include actual credentials though!

I'm on Ubuntu 18.04.4 with eksctl 0.15.0

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
$ kubectl version
```lrelease

**Logs**
Include the output of the command line when running eksctl. If possible, eksctl should be run with debug logs. For example:
`eksctl get clusters -v 4`
Make sure you redact any sensitive information before posting.
If the output is long, please consider a Gist.

**Comment by rimaulana** [comment]
Hi @jairenee 

Based on the stack trace, the issue was coming from this line 
https://github.com/weaveworks/eksctl/blob/0.15.0/pkg/ami/api.go#L57

Which is basically will check whether the BlockDeviceMappings[0] is encrypted or not. The BlockDeviceMappings is retrieved using something similar to aws ec2 describe-images.

What is special with image ami-0121d8347f8191f90 (EKS Optimized AMI for Windows 1.15 in us-east-1), block device mapping 0 is

```text
aws ec2 describe-images --image-ids ami-0121d8347f8191f90 --region us-east-1

{
    "Images": [
        {
            "VirtualizationType": "hvm",
            "Description": "Microsoft Windows Server 2019 Full optimized for EKS and provided by Amazon",
            "Hypervisor": "xen",
            "ImageOwnerAlias": "amazon",
            "EnaSupport": true,
            "SriovNetSupport": "simple",
            "ImageId": "ami-0121d8347f8191f90",
            "Platform": "windows",
            "State": "available",
            "BlockDeviceMappings": [
                {
                    "DeviceName": "xvdco",
                    "VirtualName": "ephemeral14"
                },
```

Meanwhile, for ami-07c823abadcab1ed6 (EKS Optimized AMI for Windows 1.14 in us-east-1) block device mapping 0 is

```text
aws ec2 describe-images --image-ids ami-07c823abadcab1ed6 --region us-east-1

{
    "Images": [
        {
            "VirtualizationType": "hvm",
            "Description": "Microsoft Windows Server 2019 Full optimized for EKS and provided by Amazon",
            "Hypervisor": "xen",
            "ImageOwnerAlias": "amazon",
            "EnaSupport": true,
            "SriovNetSupport": "simple",
            "ImageId": "ami-07c823abadcab1ed6",
            "Platform": "windows",
            "State": "available",
            "BlockDeviceMappings": [
                {
                    "DeviceName": "/dev/sda1",
                    "Ebs": {
                        "SnapshotId": "snap-0f050e0705cb23b48",
                        "DeleteOnTermination": true,
                        "VolumeType": "gp2",
                        "VolumeSize": 50,
                        "Encrypted": false
                    }
                },
```
Therefore, for 1.14 it works while 1.15 doesn't

**Comment by tehshwann** [comment]
(heads up - Appologies for the long post.

Looking that the images referenced above, there does seem to be a difference in the block device mapping order, but the mapping itself seems completely valid.

Here is some info I scraped using the AWSPowerShell.NetCore SDK:
### 1.14 AMI from 2020.03.11 Release
```powershell
C:\> $image = Get-EC2Image ami-07c823abadcab1ed6 -Region us-east-1
C:\> $image | Select-Object ImageId, Name, CreationDate

ImageId               Name                                                           CreationDate
-------               ----                                                           ------------
ami-07c823abadcab1ed6 Windows_Server-2019-English-Full-EKS_Optimized-1.14-2020.03.11 2020-03-11T08:37:07.000Z

C:\> $image.BlockDeviceMapping | ConvertTo-Json

[
  {
    "DeviceName": "/dev/sda1",
    "Ebs": {
      "DeleteOnTermination": true,
      "Encrypted": false,
      "Iops": 0,
      "KmsKeyId": null,
      "SnapshotId": "snap-0f050e0705cb23b48",
      "VolumeSize": 50,
      "VolumeType": "gp2"
    },
    "NoDevice": null,
    "VirtualName": null
  },
  {
    "DeviceName": "xvdca",
    "Ebs": null,
    "NoDevice": null,
    "VirtualName": "ephemeral0"
  },
  {
    "DeviceName": "xvdcb",
    "Ebs": null,
    "NoDevice": null,
    "VirtualName": "ephemeral1"
  },
  {
    "DeviceName": "xvdcc",
    "Ebs": null,
    "NoDevice": null,
    "VirtualName": "ephemeral2"
  },
  {
    "DeviceName": "xvdcd",
    "Ebs": null,
    "NoDevice": null,
    "VirtualName": "ephemeral3"
  },
  {
    "DeviceName": "xvdce",
    "Ebs": null,
    "NoDevice": null,
    "VirtualName": "ephemeral4"
  },
  {
    "DeviceName": "xvdcf",
    "Ebs": null,
    "NoDevice": null,
    "VirtualName": "ephemeral5"
  },
  {
    "DeviceName": "xvdcg",
    "Ebs": null,
    "NoDevice": null,
    "VirtualName": "ephemeral6"
  },
  {
    "DeviceName": "xvdch",
    "Ebs": null,
    "NoDevice": null,
    "VirtualName": "ephemeral7"
  },
  {
    "DeviceName": "xvdci",
    "Ebs": null,
    "NoDevice": null,
    "VirtualName": "ephemeral8"
  },
  {
    "DeviceName": "xvdcj",
    "Ebs": null,
    "NoDevice": null,
    "VirtualName": "ephemeral9"
  },
  {
    "DeviceName": "xvdck",
    "Ebs": null,
    "NoDevice": null,
    "VirtualName": "ephemeral10"
  },
  {
    "DeviceName": "xvdcl",
    "Ebs": null,
    "NoDevice": null,
    "VirtualName": "ephemeral11"
  },
  {
    "DeviceName": "xvdcm",
    "Ebs": null,
    "NoDevice": null,
    "VirtualName": "ephemeral12"
  },
  {
    "DeviceName": "xvdcn",
    "Ebs": null,
    "NoDevice": null,
    "VirtualName": "ephemeral13"
  },
  {
    "DeviceName": "xvdco",
    "Ebs": null,
    "NoDevice": null,
    "VirtualName": "ephemeral14"
  },
  {
    "DeviceName": "xvdcp",
    "Ebs": null,
    "NoDevice": null,
    "VirtualName": "ephemeral15"
  },
  {
    "DeviceName": "xvdcq",
    "Ebs": null,
    "NoDevice": null,
    "VirtualName": "ephemeral16"
  },
  {
    "DeviceName": "xvdcr",
    "Ebs": null,
    "NoDevice": null,
    "VirtualName": "ephemeral17"
  },
  {
    "DeviceName": "xvdcs",
    "Ebs": null,
    "NoDevice": null,
    "VirtualName": "ephemeral18"
  },
  {
    "DeviceName": "xvdct",
    "Ebs": null,
    "NoDevice": null,
    "VirtualName": "ephemeral19"
  },
  {
    "DeviceName": "xvdcu",
    "Ebs": null,
    "NoDevice": null,
    "VirtualName": "ephemeral20"
  },
  {
    "DeviceName": "xvdcv",
    "Ebs": null,
    "NoDevice": null,
    "VirtualName": "ephemeral21"
  },
  {
    "DeviceName": "xvdcw",
    "Ebs": null,
    "NoDevice": null,
    "VirtualName": "ephemeral22"
  },
  {
    "DeviceName": "xvdcx",
    "Ebs": null,
    "NoDevice": null,
    "VirtualName": "ephemeral23"
  },
  {
    "DeviceName": "xvdcy",
    "Ebs": null,
    "NoDevice": null,
    "VirtualName": "ephemeral24"
  },
  {
    "DeviceName": "xvdcz",
    "Ebs": null,
    "NoDevice": null,
    "VirtualName": "ephemeral25"
  }
]
```
### 1.15 AMI from 2020.03.11 Release
```powershell
C:\> $115images = Get-EC2Image -Region us-east-1 -Filter @{Name='name';Value='Windows_Server-2019-English-Full-EKS_Optimized-1.15*'}
C:\> $115image | Select-Object ImageId, Name, CreationDate


ImageId               Name                                                           CreationDate
-------               ----                                                           ------------
ami-0121d8347f8191f90 Windows_Server-2019-English-Full-EKS_Optimized-1.15-2020.03.11 2020-03-11T09:04:23.000Z

C:\> $115image.BlockDeviceMapping | ConvertTo-Json

[
  {
    "DeviceName": "/dev/sda1",
    "Ebs": {
      "DeleteOnTermination": true,
      "Encrypted": false,
      "Iops": 0,
      "KmsKeyId": null,
      "SnapshotId": "snap-0c1a18af22030f7a0",
      "VolumeSize": 50,
      "VolumeType": "gp2"
    },
    "NoDevice": null,
    "VirtualName": null
  },
  {
    "DeviceName": "xvdca",
    "Ebs": null,
    "NoDevice": null,
    "VirtualName": "ephemeral0"
  },
  {
    "DeviceName": "xvdcb",
    "Ebs": null,
    "NoDevice": null,
    "VirtualName": "ephemeral1"
  },
  {
    "DeviceName": "xvdcc",
    "Ebs": null,
    "NoDevice": null,
    "VirtualName": "ephemeral2"
  },
  {
    "DeviceName": "xvdcd",
    "Ebs": null,
    "NoDevice": null,
    "VirtualName": "ephemeral3"
  },
  {
    "DeviceName": "xvdce",
    "Ebs": null,
    "NoDevice": null,
    "VirtualName": "ephemeral4"
  },
  {
    "DeviceName": "xvdcf",
    "Ebs": null,
    "NoDevice": null,
    "VirtualName": "ephemeral5"
  },
  {
    "DeviceName": "xvdcg",
    "Ebs": null,
    "NoDevice": null,
    "VirtualName": "ephemeral6"
  },
  {
    "DeviceName": "xvdch",
    "Ebs": null,
    "NoDevice": null,
    "VirtualName": "ephemeral7"
  },
  {
    "DeviceName": "xvdci",
    "Ebs": null,
    "NoDevice": null,
    "VirtualName": "ephemeral8"
  },
  {
    "DeviceName": "xvdcj",
    "Ebs": null,
    "NoDevice": null,
    "VirtualName": "ephemeral9"
  },
  {
    "DeviceName": "xvdck",
    "Ebs": null,
    "NoDevice": null,
    "VirtualName": "ephemeral10"
  },
  {
    "DeviceName": "xvdcl",
    "Ebs": null,
    "NoDevice": null,
    "VirtualName": "ephemeral11"
  },
  {
    "DeviceName": "xvdcm",
    "Ebs": null,
    "NoDevice": null,
    "VirtualName": "ephemeral12"
  },
  {
    "DeviceName": "xvdcn",
    "Ebs": null,
    "NoDevice": null,
    "VirtualName": "ephemeral13"
  },
  {
    "DeviceName": "xvdco",
    "Ebs": null,
    "NoDevice": null,
    "VirtualName": "ephemeral14"
  },
  {
    "DeviceName": "xvdcp",
    "Ebs": null,
    "NoDevice": null,
    "VirtualName": "ephemeral15"
  },
  {
    "DeviceName": "xvdcq",
    "Ebs": null,
    "NoDevice": null,
    "VirtualName": "ephemeral16"
  },
  {
    "DeviceName": "xvdcr",
    "Ebs": null,
    "NoDevice": null,
    "VirtualName": "ephemeral17"
  },
  {
    "DeviceName": "xvdcs",
    "Ebs": null,
    "NoDevice": null,
    "VirtualName": "ephemeral18"
  },
  {
    "DeviceName": "xvdct",
    "Ebs": null,
    "NoDevice": null,
    "VirtualName": "ephemeral19"
  },
  {
    "DeviceName": "xvdcu",
    "Ebs": null,
    "NoDevice": null,
    "VirtualName": "ephemeral20"
  },
  {
    "DeviceName": "xvdcv",
    "Ebs": null,
    "NoDevice": null,
    "VirtualName": "ephemeral21"
  },
  {
    "DeviceName": "xvdcw",
    "Ebs": null,
    "NoDevice": null,
    "VirtualName": "ephemeral22"
  },
  {
    "DeviceName": "xvdcx",
    "Ebs": null,
    "NoDevice": null,
    "VirtualName": "ephemeral23"
  },
  {
    "DeviceName": "xvdcy",
    "Ebs": null,
    "NoDevice": null,
    "VirtualName": "ephemeral24"
  },
  {
    "DeviceName": "xvdcz",
    "Ebs": null,
    "NoDevice": null,
    "VirtualName": "ephemeral25"
  }
]
```
**Notice:** All the devices are there... they just arent sorted alphabetically:
```powershell
C:\> $114image.BlockDeviceMapping.DeviceName
/dev/sda1
xvdca
xvdcb
xvdcc
xvdcd
xvdce
xvdcf
xvdcg
xvdch
xvdci
xvdcj
xvdck
xvdcl
xvdcm
xvdcn
xvdco
xvdcp
xvdcq
xvdcr
xvdcs
xvdct
xvdcu
xvdcv
xvdcw
xvdcx
xvdcy
xvdcz
C:\> $115image.BlockDeviceMapping.DeviceName
xvdco
xvdcp
xvdcm
xvdcn
xvdcs
xvdct
xvdcq
xvdcr
xvdcw
xvdcx
xvdcu
xvdcv
xvdcy
xvdcz
xvdcc
xvdcd
xvdca
xvdcb
xvdcg
xvdch
xvdce
xvdcf
xvdck
xvdcl
xvdci
xvdcj
/dev/sda1
C:\> $115image.BlockDeviceMapping.DeviceName | sort
/dev/sda1
xvdca
xvdcb
xvdcc
xvdcd
xvdce
xvdcf
xvdcg
xvdch
xvdci
xvdcj
xvdck
xvdcl
xvdcm
xvdcn
xvdco
xvdcp
xvdcq
xvdcr
xvdcs
xvdct
xvdcu
xvdcv
xvdcw
xvdcx
xvdcy
xvdcz
```

I wasnt able to confirm but it appears that eksctl is expecting index `0` of the blockdevicemapping list to always be the root volume. If this is the case, this is a flawed assumption. If eksctl is referencing `[Amazon.EC2.Model.BlockDeviceMapping[]]` list using a `0` index blindly and not correctly treating this as an un-ordered map... this could be the issue.

Assuming this is the case, eksctl should be updated to use more explicit logic for finding the root volume. For example, when trying to find the EC2 Windows root volume of an AMI, one should filter the block device mapping looking for the documented default mount point of `/dev/sda1`:
```powershell
C:\> $115image.BlockDeviceMapping

DeviceName Ebs                             NoDevice VirtualName
---------- ---                             -------- -----------
xvdco                                               ephemeral14
xvdcp                                               ephemeral15
xvdcm                                               ephemeral12
xvdcn                                               ephemeral13
xvdcs                                               ephemeral18
xvdct                                               ephemeral19
xvdcq                                               ephemeral16
xvdcr                                               ephemeral17
xvdcw                                               ephemeral22
xvdcx                                               ephemeral23
xvdcu                                               ephemeral20
xvdcv                                               ephemeral21
xvdcy                                               ephemeral24
xvdcz                                               ephemeral25
xvdcc                                               ephemeral2
xvdcd                                               ephemeral3
xvdca                                               ephemeral0
xvdcb                                               ephemeral1
xvdcg                                               ephemeral6
xvdch                                               ephemeral7
xvdce                                               ephemeral4
xvdcf                                               ephemeral5
xvdck                                               ephemeral10
xvdcl                                               ephemeral11
xvdci                                               ephemeral8
xvdcj                                               ephemeral9
/dev/sda1  Amazon.EC2.Model.EbsBlockDevice

C:\> $115image.BlockDeviceMapping | Where-Object {$_.DeviceName -eq '/dev/sda1'}

DeviceName Ebs                             NoDevice VirtualName
---------- ---                             -------- -----------
/dev/sda1  Amazon.EC2.Model.EbsBlockDevice

C:\> $rootDevice = $115image.BlockDeviceMapping | Where-Object {$_.DeviceName -eq '/dev/sda1'}
C:\> $rootDevice | ConvertTo-Json
{
  "DeviceName": "/dev/sda1",
  "Ebs": {
    "DeleteOnTermination": true,
    "Encrypted": false,
    "Iops": 0,
    "KmsKeyId": null,
    "SnapshotId": "snap-0c1a18af22030f7a0",
    "VolumeSize": 50,
    "VolumeType": {
      "Value": "gp2"
    }
  },
  "NoDevice": null,
  "VirtualName": null
}
C:\> $randomDeviceAtIndex0 = $115image.BlockDeviceMapping[0]
C:\> $randomDeviceAtIndex0 | ConvertTo-Json
{
  "DeviceName": "xvdco",
  "Ebs": null,
  "NoDevice": null,
  "VirtualName": "ephemeral14"
}
C:\>
```
