### ISSUE TITLE
Create nodegroup panics on partial vpc subnet config

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/eksctl#2923]
**What happened?**

I was being lazy and did a half subnet config thing:

```yaml
vpc:
  id: vpc-foo
  cidr: "192.168.0.0/16"
  subnets:
    public:
      public-one:
        id: subnet-bar
# no private subnets
```

**What you expected to happen?**

I hoped I would get away with it, but at least a nice error telling me to do it properly.

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
0.34.0
```

**Logs**

```sh
eksctl create nodegroup -f config.yaml
[ℹ]  eksctl version 0.34.0
[ℹ]  using region us-west-2
[ℹ]  will use version 1.18 for new nodegroup(s) based on control plane version
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/weaveworks/eksctl/pkg/apis/eksctl.io/v1alpha5.doImportSubnet(0x0, 0xc0009bd220, 0xa, 0xc00068f4a0, 0x18, 0xc0009bd130, 0x10, 0x0, 0x0)
        github.com/weaveworks/eksctl/pkg/apis/eksctl.io/v1alpha5/vpc.go:259 +0xb66
github.com/weaveworks/eksctl/pkg/apis/eksctl.io/v1alpha5.(*ClusterConfig).ImportSubnet(0xc000230a20, 0x355b9da, 0x7, 0xc0009bd220, 0xa, 0xc00068f4a0, 0x18, 0xc0009bd130, 0x10, 0x19e44dd, ...)
        github.com/weaveworks/eksctl/pkg/apis/eksctl.io/v1alpha5/vpc.go:211 +0x2e8
github.com/weaveworks/eksctl/pkg/vpc.ImportSubnets(0x3aa4500, 0xc00053dd60, 0xc000230a20, 0x355b9da, 0x7, 0xc0009bb1c0, 0x3, 0x3, 0x0, 0x0)
        github.com/weaveworks/eksctl/pkg/vpc/vpc.go:266 +0x185
github.com/weaveworks/eksctl/pkg/vpc.ImportSubnetsFromList(0x3aa4500, 0xc00053dd60, 0xc000230a20, 0x355b9da, 0x7, 0xc0007ac060, 0x3, 0x3, 0x3, 0x0)
        github.com/weaveworks/eksctl/pkg/vpc/vpc.go:287 +0xcb
github.com/weaveworks/eksctl/pkg/vpc.UseFromCluster.func4(0xc000b5b7c0, 0x4a, 0x1, 0x0)
        github.com/weaveworks/eksctl/pkg/vpc/vpc.go:185 +0xd3
github.com/weaveworks/eksctl/pkg/cfn/outputs.(*CollectorSet).doCollect(0xc000e8efd0, 0xc000102c00, 0xc000183a58, 0x1, 0x1, 0x0, 0xc000809120, 0x0, 0xc00038b048, 0xc0009df698, ...)
        github.com/weaveworks/eksctl/pkg/cfn/outputs/api.go:90 +0x2ec
github.com/weaveworks/eksctl/pkg/cfn/outputs.Collect(0xc000183a58, 0x1, 0x1, 0x0, 0xc000809120, 0x0, 0xc00038b048, 0xc0009df698, 0xc0009fa0b0, 0xc0009df750, ...)
        github.com/weaveworks/eksctl/pkg/cfn/outputs/api.go:104 +0x98
github.com/weaveworks/eksctl/pkg/vpc.UseFromCluster(0x3aa4500, 0xc00053dd60, 0xc00086a600, 0xc000230a20, 0x6, 0xc000916b60)
        github.com/weaveworks/eksctl/pkg/vpc/vpc.go:203 +0x5d8
github.com/weaveworks/eksctl/pkg/eks.(*ClusterProvider).LoadClusterVPC(0xc000230b20, 0xc000230a20, 0x2b12960, 0xc000e36020)
        github.com/weaveworks/eksctl/pkg/eks/eks.go:290 +0xa5
github.com/weaveworks/eksctl/pkg/eks.(*ClusterProvider).LoadClusterIntoSpec(0xc000230b20, 0xc000230a20, 0x0, 0x0)
        github.com/weaveworks/eksctl/pkg/eks/eks.go:271 +0x39
github.com/weaveworks/eksctl/pkg/actions/create.(*NodeGroup).Create(0xc000230a20, 0xc000230a20, 0x0)
        github.com/weaveworks/eksctl/pkg/actions/create/nodegroup.go:73 +0x107
github.com/weaveworks/eksctl/pkg/ctl/create.createNodeGroupCmd.func1(0xc00087a8f0, 0xc000868630, 0x10101, 0x0, 0x0, 0x0, 0x0, 0xc000b0fd20, 0x1df0d9d)
        github.com/weaveworks/eksctl/pkg/ctl/create/nodegroup.go:37 +0x246
github.com/weaveworks/eksctl/pkg/ctl/create.createNodeGroupCmdWithRunFunc.func1(0xc0002bcb00, 0xc000781620, 0x0, 0x2, 0x0, 0x0)
        github.com/weaveworks/eksctl/pkg/ctl/create/nodegroup.go:60 +0x104
github.com/spf13/cobra.(*Command).execute(0xc0002bcb00, 0xc0007815e0, 0x2, 0x2, 0xc0002bcb00, 0xc0007815e0)
        github.com/spf13/cobra@v1.1.1/command.go:850 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002bc2c0, 0xc0002fe410, 0x1, 0xc000b0ff70)
        github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.1.1/command.go:895
main.main()
        github.com/weaveworks/eksctl/cmd/eksctl/main.go:76 +0x3ec
```

**Comment by aclevername** [comment]
Fixed in https://github.com/weaveworks/eksctl/pull/2928
