### ISSUE TITLE
Runtime error: nil pointer dereference when VPC is empty

### ISSUE THREAD

**Issue by liranp** [weaveworks/eksctl#3442]
**What were you trying to accomplish?**
Create an unmanaged nodegroup.

**What happened?**
Runtime error (eksctl panics).

**How to reproduce it?**
Either a `create cluster` or a `create nodegroup` command can be invoked with a config file with no VPC configuration.

**Logs**
```sh
$ eksctl create nodegroup -f /path/to/cluster.yaml -v 4 

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x245e974]

goroutine 1 [running]:
github.com/weaveworks/eksctl/pkg/apis/eksctl.io/v1alpha5.SetClusterConfigDefaults(0xc0006c37a0)
	go/src/github.com/weaveworks/eksctl/pkg/apis/eksctl.io/v1alpha5/defaults.go:55 +0x1b4
github.com/weaveworks/eksctl/pkg/ctl/cmdutils.(*Cmd).NewCtl(0xc0000b82c0, 0x0, 0x0, 0x0)
	go/src/github.com/weaveworks/eksctl/pkg/ctl/cmdutils/cmd.go:33 +0x45
github.com/weaveworks/eksctl/pkg/ctl/create.createNodeGroupCmd.func1(0xc0000b82c0, 0xc000456e10, 0x10101, 0x0, 0x0, 0x0, 0x0, 0xc000456e00, 0x0, 0x0, ...)
	go/src/github.com/weaveworks/eksctl/pkg/ctl/create/nodegroup.go:24 +0xcc
github.com/weaveworks/eksctl/pkg/ctl/create.createNodeGroupCmdWithRunFunc.func1(0xc0004e5680, 0xc0003a7f00, 0x0, 0x4, 0x0, 0x0)
	go/src/github.com/weaveworks/eksctl/pkg/ctl/create/nodegroup.go:63 +0x14d
github.com/spf13/cobra.(*Command).execute(0xc0004e5680, 0xc0003a7ec0, 0x4, 0x4, 0xc0004e5680, 0xc0003a7ec0)
	go/src/github.com/weaveworks/eksctl/vendor/github.com/spf13/cobra/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc0004e4a00, 0xc0003940e0, 0x1, 0xc000a3ff70)
	go/src/github.com/weaveworks/eksctl/vendor/github.com/spf13/cobra/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	go/src/github.com/weaveworks/eksctl/vendor/github.com/spf13/cobra/command.go:897
main.main()
	go/src/github.com/weaveworks/eksctl/cmd/eksctl/main.go:76 +0x41b
```

**Anything else we need to know?**
Introduced by #3027.

**Versions**
```
$ eksctl version
0.42.0-dev+75f5eec9.2021-03-17T15:33:59Z
```

**Comment by liranp** [comment]
Fixed by #3447.
