### ISSUE TITLE
Error when trying to create unmanaged nodegroup in cloudformation cluster

### ISSUE THREAD

**Issue by tobias-zeptio** [weaveworks/eksctl#3484]
I get a error when I try to create an unmanaged nodegroup for a cluster created through cloudformation.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1e4edb8]

goroutine 1 [running]:
github.com/weaveworks/eksctl/pkg/vpc.cleanupSubnets(0xc0006a6e00)
        github.com/weaveworks/eksctl/pkg/vpc/vpc.go:529 +0x138
github.com/weaveworks/eksctl/pkg/vpc.ImportSubnetsFromSpec(0x3414528, 0xc0003320c0, 0xc0006a6e00, 0x0, 0x0)
        github.com/weaveworks/eksctl/pkg/vpc/vpc.go:492 +0x11a
github.com/weaveworks/eksctl/pkg/actions/nodegroup.loadVPCFromConfig(0x3414528, 0xc0003320c0, 0xc0006a6e00, 0x1, 0x1)
        github.com/weaveworks/eksctl/pkg/actions/nodegroup/create.go:282 +0x69
github.com/weaveworks/eksctl/pkg/actions/nodegroup.(*Manager).Create(0xc0006612c0, 0xc000010101, 0xc000a82000, 0x0, 0xc000421890, 0xc0004218c0, 0x0, 0x339e920)
        github.com/weaveworks/eksctl/pkg/actions/nodegroup/create.go:50 +0x2ef
github.com/weaveworks/eksctl/pkg/ctl/create.createNodeGroupCmd.func1(0xc0008b3b80, 0xc0008be900, 0x10101, 0x0, 0x0, 0x0, 0x0, 0xc000a1fd18, 0x1f685fd)
        github.com/weaveworks/eksctl/pkg/ctl/create/nodegroup.go:40 +0x214
github.com/weaveworks/eksctl/pkg/ctl/create.createNodeGroupCmdWithRunFunc.func1(0xc00069cf00, 0xc0009481c0, 0x0, 0xe, 0x0, 0x0)
        github.com/weaveworks/eksctl/pkg/ctl/create/nodegroup.go:62 +0x10a
github.com/spf13/cobra.(*Command).execute(0xc00069cf00, 0xc0009480e0, 0xe, 0xe, 0xc00069cf00, 0xc0009480e0)
        github.com/spf13/cobra@v1.1.3/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc00069c280, 0xc000384670, 0x1, 0xc000a1ff70)
        github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
        github.com/weaveworks/eksctl/cmd/eksctl/main.go:76 +0x41b
```

This is the command I run:

```
eksctl create nodegroup \
    --cluster husqiot-eks-dev \
    --node-type t3a.small \
    --node-ami auto \
    --nodes 1 \
    --nodes-min 1 \
    --nodes-max 2 \
    --max-pods-per-node 100
```

And this is the cloudformation:

```
  ServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "eks-servicerole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - eks.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy

  EKSCluster:
    Type: "AWS::EKS::Cluster"
    Properties:
      Name: !Sub "husqiot-eks-dev"
      Version: "1.19"
      RoleArn: !GetAtt ServiceRole.Arn
      ResourcesVpcConfig:
        SubnetIds:
          Fn::Split:
            - ","
            - Fn::Join:
                - ","
                - - Fn::ImportValue: !Sub "${NetworkingStackName}-PublicSubnets"
                  - Fn::ImportValue: !Sub "${NetworkingStackName}-PrivateSubnets"
```

**Versions**
```
eksctl 0.41.0
kubectl 
   client 1.19.6
   server 1.19.6-eks-49a6c0
```

**Comment by aclevername** [comment]
Thanks for opening the issue @tobias-zeptio . The docs for this functionality hasn't been pushed to our live site yet, but you can find it [here](https://github.com/weaveworks/eksctl/blob/6c120df97f32912c4bdefe3fe0bb93840dde2bd5/userdocs/src/usage/unowned-clusters.md#creating-nodegroups). You need to provide a VPC spec in the cfg file when creating nodegroups for clusters not created by eksctl

**Comment by Callisto13** [comment]
gah, just saw a typo in the example yaml 🤦‍♀️

**Comment by Callisto13** [comment]
i will also pr a thing so that a nice error is returned if no vpc conf is provided. could have sworn i already did that but maybe i only go as far as thinking about it
