### ISSUE TITLE
cluster delete panics if default ~/kube/config doesn't exist and can't be locked*

### ISSUE THREAD

**Issue by wongma7** [weaveworks/eksctl#3801]
**What were you trying to accomplish?**

call `eksctl cluster delete` in an AWS Lambda where there is no ~/.kube directory and the filesystem is read-only

**What happened?**

deletion failed and eksctl panicked. eksctl is trying to remove the cluster context from my "global" .kube/config but I don't have a .kube/config. eksctl should no-op and continue with deletion instead of panicking.

stacktrace if ~/.kube exists but is read-only so ~/.kube/config can't be locked*:
```
2021-06-03 12:56:14 [ℹ]  deleted 0 Fargate profile(s)
2021-06-03 12:56:15 [✖]  failed to obtain exclusive lock on kubeconfig lockfile: open /home/matthew/.kube/config.eksctl.lock: read-only file system
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1e5575b]

goroutine 1 [running]:
github.com/gofrs/flock.(*Flock).Unlock(0x0, 0x0, 0x0)
	github.com/gofrs/flock@v0.8.0/flock_unix.go:87 +0x3b
github.com/weaveworks/eksctl/pkg/utils/kubeconfig.unlockConfigFile(0x0, 0x10, 0x1)
	github.com/weaveworks/eksctl/pkg/utils/kubeconfig/kubeconfig.go:214 +0x2f
github.com/weaveworks/eksctl/pkg/utils/kubeconfig.MaybeDeleteConfig.func2(0x0)
	github.com/weaveworks/eksctl/pkg/utils/kubeconfig/kubeconfig.go:346 +0x2b
github.com/weaveworks/eksctl/pkg/utils/kubeconfig.MaybeDeleteConfig(0xc0005c87c0)
	github.com/weaveworks/eksctl/pkg/utils/kubeconfig/kubeconfig.go:366 +0x8a5
github.com/weaveworks/eksctl/pkg/actions/cluster.deleteSharedResources(0xc000330900, 0xc000585c38, 0x34622d8, 0xc000327c30, 0x1, 0x345ff78, 0xc00098d080, 0x0, 0x0)
	github.com/weaveworks/eksctl/pkg/actions/cluster/delete.go:41 +0x13a
github.com/weaveworks/eksctl/pkg/actions/cluster.(*OwnedCluster).Delete(0xc00098af60, 0x4a817c800, 0x33f0000, 0xc00098af60, 0x0)
	github.com/weaveworks/eksctl/pkg/actions/cluster/owned.go:104 +0xd1
github.com/weaveworks/eksctl/pkg/ctl/delete.doDeleteCluster(0xc0007e7130, 0x0, 0x1, 0x7ffe18bd3a1a)
	github.com/weaveworks/eksctl/pkg/ctl/delete/cluster.go:73 +0x296
github.com/weaveworks/eksctl/pkg/ctl/delete.deleteClusterCmd.func1(0xc0003e9180, 0xc0008c7410, 0x1, 0x1, 0x0, 0x0)
	github.com/weaveworks/eksctl/pkg/ctl/delete/cluster.go:26 +0x8a
github.com/spf13/cobra.(*Command).execute(0xc0003e9180, 0xc0008c73e0, 0x1, 0x1, 0xc0003e9180, 0xc0008c73e0)
	github.com/spf13/cobra@v1.1.3/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc00094ec80, 0xc0008c72f0, 0x1, 0xc000a1ff70)
	github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
	github.com/weaveworks/eksctl/cmd/eksctl/main.go:76 +0x41b
```
**How to reproduce it?**

Locally:
1. create a cluster x
2. make your .kube read-only `mkdir /tmp/readonlykube && sudo mount --bind -o ro /tmp/readonlykube ~/.kube`
3. execute `eksctl cluster delete x`
4. eksctl panics

**Logs**

stacktrace above

**Anything else we need to know?**

 https://github.com/weaveworks/eksctl/blob/8ab886b8752038a3ee521aa30dc356468211c6f0/pkg/utils/kubeconfig/kubeconfig.go#L338.
lockConfigFile fails to lock .kube/config, so fl is nil
fl.unlockConfigFile is called, so eksctl panics.

**Versions**

```
$ eksctl version
0.51.0
$ kubectl version
```

**Comment by cPu1** [comment]
Fixed by https://github.com/weaveworks/eksctl/pull/3802
