### ISSUE TITLE
Ubuntu AMIs for K8s 1.20 fail to find credentials

### ISSUE THREAD

**Issue by mpitt** [weaveworks/eksctl#3859]
**What were you trying to accomplish?**
Creating a new nodegroup after upgrading the cluster to 1.20. I was using an AMI based on the Ubuntu AMI for EKS version 1.20 (20210609). 

**What happened?**
The nodes failed to join the cluster. I inspected the logs of the kubelet on a node and found this.

```
2021-06-15T15:01:48Z kubelet-eks.daemon[15992]: E0615 15:01:48.247341   15992 reflector.go:138] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:46: Failed to watch *v1.Pod: failed
 to list *v1.Pod: Get "https://[redacted].eu-west-1.eks.amazonaws.com/api/v1/pods?fieldSelector=spec.nodeName%3Dip-172-30-10-18.eu-west-1.compute.internal&
limit=500&resourceVersion=0": getting credentials: exec: executable heptio-authenticator-aws not found
2021-06-15T15:01:48Z kubelet-eks.daemon[15992]: It looks like you are trying to use a client-go credential plugin that is not installed.
2021-06-15T15:01:48Z kubelet-eks.daemon[15992]: To learn more about this feature, consult the documentation available at:
2021-06-15T15:01:48Z kubelet-eks.daemon[15992]:       https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins
```

**How to reproduce it?**

```
eksctl create nodegroup --config-file cluster.yaml
```

<details>
<summary>cluster.yaml</summary>

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-prod-1
  region: eu-west-1
  version: "1.20"

vpc:
  id: vpc-***
  cidr: 172.30.0.0/16
  subnets:
    # must provide 'private' and/or 'public' subnets by availibility zone as shown
    private:
      eu-west-1a: {id: subnet-***}
      eu-west-1b: {id: subnet-***}
      eu-west-1c: {id: subnet-***}
    public:
      eu-west-1a: {id: subnet-***}
      eu-west-1b: {id: subnet-***}
      eu-west-1c: {id: subnet-***}

nodeGroups:
  - name: standard-workers-11
    minSize: 8
    maxSize: 8
    desiredCapacity: 8
    labels:
      role: workers
      lifecycle: Ec2OnDemand
    instanceType: t3a.xlarge
    ami: ami-***
    amiFamily: Ubuntu2004
    kubeletExtraConfig:
      evictionHard:
        nodefs.available: "20%"
    ssh:
      publicKeyName: production
    tags:
      Name: EksWorkers1
      Group: infra
      Project: infrastructure
      Component: k8s
      Application: k8s
      Environment: production
    preBootstrapCommands:
      - do-ansible-pull eks.yml
    securityGroups:
      attachIDs: ["sg-***"]
    volumeSize: 80
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
        # [...]
      withAddonPolicies:
        ebs: true

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

iam:
  withOIDC: true
```
</details>

**Logs**

<details>
<summary>eksctl output</summary>

```
2021-06-15 16:53:04 [ℹ]  eksctl version 0.53.0
2021-06-15 16:53:04 [ℹ]  using region eu-west-1
2021-06-15 16:53:06 [!]  Custom AMI detected for nodegroup standard-workers-11. Please refer to https://github.com/weaveworks/eksctl/issues/3563 for upcoming breaking changes
2021-06-15 16:53:06 [ℹ]  nodegroup "standard-workers-11" will use "ami-0a79ea87240daa549" [Ubuntu2004/1.20]
[...]
2021-06-15 16:53:15 [ℹ]  checking cluster stack for missing resources
2021-06-15 16:53:16 [ℹ]  cluster stack has all required resources
2021-06-15 16:53:16 [ℹ]  building nodegroup stack "eksctl-eks-prod-1-nodegroup-standard-workers-11"
2021-06-15 16:53:16 [!]  Custom AMI detected for nodegroup standard-workers-11, using legacy nodebootstrap mechanism. Please refer to https://github.com/weaveworks/eksctl/issues/3563 for upcoming breaking changes
2021-06-15 16:53:17 [ℹ]  deploying stack "eksctl-eks-prod-1-nodegroup-standard-workers-11"
2021-06-15 16:53:17 [ℹ]  waiting for CloudFormation stack "eksctl-eks-prod-1-nodegroup-standard-workers-11"
2021-06-15 16:53:35 [ℹ]  waiting for CloudFormation stack "eksctl-eks-prod-1-nodegroup-standard-workers-11"
[...]
2021-06-15 16:57:34 [ℹ]  waiting for CloudFormation stack "eksctl-eks-prod-1-nodegroup-standard-workers-11"
2021-06-15 16:57:35 [ℹ]  no tasks
2021-06-15 16:57:35 [ℹ]  adding identity "arn:aws:iam::107593380771:role/eksctl-eks-prod-1-nodegroup-stand-NodeInstanceRole-1EU5YO2L7WB7H" to auth ConfigMap
2021-06-15 16:57:35 [ℹ]  nodegroup "standard-workers-11" has 0 node(s)
2021-06-15 16:57:35 [ℹ]  waiting for at least 8 node(s) to become ready in "standard-workers-11"
Error: timed out (after 25m0s) waiting for at least 8 nodes to join the cluster and become ready in "standard-workers-11"
```
</details>

**Anything else we need to know?**

**Versions**

```
$ eksctl version
0.53.0
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:11:29Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-eks-6b7464", GitCommit:"6b746440c04cb81db4426842b4ae65c3f7035e53", GitTreeState:"clean", BuildDate:"2021-03-19T19:33:03Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by cPu1** [comment]
The issue here is you're using a custom AMI by setting the `ami` field and that has triggered the legacy code path that's still using the `heptio-authenticator-aws` authenticator, but it appears that Ubuntu 20.04 AMIs do not ship with that binary. We'll work on this soon.

**Comment by ilpianista** [comment]
@cPu1 FYI the AMI has neither `heptio-authenticator-aws` nor `aws-iam-authenticator`. Also, `aws eks get-token` returns:

```
ImportError: cannot import name 'docevents' from 'botocore.docs.bcdoc' (/usr/local/lib/python3.8/dist-packages/botocore/docs/bcdoc/__init__.py)
    from botocore.docs.bcdoc import docevents
  File "/usr/lib/python3/dist-packages/awscli/help.py", line 23, in <module>
    from awscli.help import ProviderHelpCommand
  File "/usr/lib/python3/dist-packages/awscli/clidriver.py", line 36, in <module>
    import awscli.clidriver
  File "/usr/bin/aws", line 19, in <module>
Traceback (most recent call last):
```

I also filled [a bug upstream](https://bugs.launchpad.net/cloud-images/+bug/1932049).

**Comment by ilpianista** [comment]
So, we realized that we installed some python library that broke the awscli. `aws eks get-token` works fine in the AMI and I think `eksctl` should be updated to use that one instead of `heptio`.

**Comment by cPu1** [comment]
> So, we realized that we installed some python library that broke the awscli. `aws eks get-token` works fine in the AMI and I think `eksctl` should be updated to use that one instead of `heptio`.

Thanks for looking into it. We'll work on it.
