### ISSUE TITLE
eksctl create nodegroup error with instance selector parameters

### ISSUE THREAD

**Issue by ashwinikumar-sa** [weaveworks/eksctl#3982]
**What were you trying to accomplish?**

```
eksctl create nodegroup \
 --cluster eksworkshop-eksctl \
 --region us-east-1 \
 --name dev-8vcpu-32gb-spot \
 --nodes-min 1 \
 --nodes-max 5 \
 --managed \
 --spot \
 --instance-selector-vcpus=8 \
 --instance-selector-memory=32 \
 --instance-selector-cpu-architecture=x86_64 \
 --instance-selector-gpus=0
```

**What happened?**

```
2021-07-16 15:54:57 [ℹ]  eksctl version 0.57.0
2021-07-16 15:54:57 [ℹ]  using region us-east-1
2021-07-16 15:54:57 [ℹ]  will use version 1.20 for new nodegroup(s) based on control plane version
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1fd3b69]

goroutine 1 [running]:
github.com/weaveworks/eksctl/pkg/eks.(*NodeGroupService).expandInstanceSelector(0xc0007c0840, 0xc0004c5d10, 0xc000701c80, 0x4, 0x4, 0x7f4336df93b8, 0x7f4337070b78, 0x10, 0x10, 0x7f435dccd108)
        github.com/weaveworks/eksctl/pkg/eks/nodegroup_service.go:207 +0x1a9
github.com/weaveworks/eksctl/pkg/eks.(*NodeGroupService).ExpandInstanceSelectorOptions(0xc0007c0840, 0xc00062baa0, 0x1, 0x1, 0xc000701c80, 0x4, 0x4, 0x0, 0xc0003b5a40)
        github.com/weaveworks/eksctl/pkg/eks/nodegroup_service.go:139 +0x215
github.com/weaveworks/eksctl/pkg/actions/nodegroup.(*Manager).Create(0xc0003b5a40, 0x10101, 0x34d1de0, 0xc0004c79a0, 0xc0003b5a40, 0x0)
        github.com/weaveworks/eksctl/pkg/actions/nodegroup/create.go:81 +0x4a2
github.com/weaveworks/eksctl/pkg/ctl/create.createNodeGroupCmd.func1(0xc000532790, 0xc000365e00, 0x101, 0x101, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0)
        github.com/weaveworks/eksctl/pkg/ctl/create/nodegroup.go:60 +0x3c5
github.com/weaveworks/eksctl/pkg/ctl/create.createNodeGroupCmdWithRunFunc.func1(0xc00037f400, 0xc000622400, 0x0, 0x10, 0x0, 0x0)
        github.com/weaveworks/eksctl/pkg/ctl/create/nodegroup.go:86 +0x106
github.com/spf13/cobra.(*Command).execute(0xc00037f400, 0xc000622300, 0x10, 0x10, 0xc00037f400, 0xc000622300)
        github.com/spf13/cobra@v1.2.1/command.go:856 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc00037e000, 0xc000066990, 0x1, 0xc0007dff70)
        github.com/spf13/cobra@v1.2.1/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
        github.com/weaveworks/eksctl/cmd/eksctl/main.go:77 +0x41b
```

**How to reproduce it?**
Create an EKS Cluster with eksctl create cluster first and try to add a managed nodegroup with above command and you will be able to reproduce the error (Tried with latest version of eksctl version 0.57.0)

**Logs**

**Anything else we need to know?**
What OS are you using? 
Amazon Linux2

Are you using a downloaded binary or did you compile eksctl?
 downloaded binary with following steps
```
curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
sudo mv /tmp/eksctl /usr/local/bin
```

**Versions**
eksctl version
0.57.0
EKS cluster version 1.20 (tried with 1.18, 1.19 also) same error

**Comment by Callisto13** [comment]
Thanks for reporting @ashwinikumar-sa 👍 

Fix notes for me on Monday (or whoever picks this up:
After a quick test it looks like `m.instanceSelector` is `nil` here: https://github.com/weaveworks/eksctl/blob/main/pkg/eks/nodegroup_service.go#L207
