### ISSUE TITLE
Using --instance-selector-cpu-architecture arm64 cause a panic.

### ISSUE THREAD

**Issue by ohmakoto** [weaveworks/eksctl#4067]
**What were you trying to accomplish?**

```
eksctl create nodegroup \
--cluster LatestOcean \
--name AMZN-Linux2-arm64 \
--node-ami-family AmazonLinux2 \
--spot \
--instance-selector-cpu-architecture arm64 \
--instance-types t4g.medium,t4g.large,t4g.small
```
**What happened?**
When I ran the command, a panic ensued.

**How to reproduce it?**
I was trying to add a managed node group to an existing cluster.
The managed node group is AmazonLinux2, CPU architecture is Arm64, and instance type is t4g.medium,t4g.large,t4g.small.

**Logs**
```
2021-08-10 16:44:19 [ℹ]  eksctl version 0.60.0
2021-08-10 16:44:19 [ℹ]  using region ap-northeast-1
2021-08-10 16:44:20 [ℹ]  will use version 1.21 for new nodegroup(s) based on control plane version
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x2e51c89]

goroutine 1 [running]:
github.com/weaveworks/eksctl/pkg/eks.(*NodeGroupService).expandInstanceSelector(0xc000be7da0, 0xc000394a50, 0xc000cfeac0, 0x3, 0x4, 0x7679b38, 0xeac90a0, 0x10, 0x10, 0x658a5b8)
	github.com/weaveworks/eksctl/pkg/eks/nodegroup_service.go:207 +0x1a9
github.com/weaveworks/eksctl/pkg/eks.(*NodeGroupService).ExpandInstanceSelectorOptions(0xc000be7da0, 0xc000b36dd0, 0x1, 0x1, 0xc000cfeac0, 0x3, 0x4, 0x0, 0x7527fd0)
	github.com/weaveworks/eksctl/pkg/eks/nodegroup_service.go:139 +0x215
github.com/weaveworks/eksctl/pkg/actions/nodegroup.(*Manager).Create(0xc000badb00, 0x10101, 0x44a0bd0, 0xc000543dc0, 0xc000badb00, 0x0)
	github.com/weaveworks/eksctl/pkg/actions/nodegroup/create.go:81 +0x4a2
github.com/weaveworks/eksctl/pkg/ctl/create.createNodeGroupCmd.func1(0xc0001622c0, 0xc0009c3a40, 0x101, 0x101, 0xc0009281e0, 0x3, 0x3, 0x1, 0x0, 0x0)
	github.com/weaveworks/eksctl/pkg/ctl/create/nodegroup.go:60 +0x3c5
github.com/weaveworks/eksctl/pkg/ctl/create.createNodeGroupCmdWithRunFunc.func1(0xc00054cf00, 0xc0002f9ee0, 0x0, 0xd, 0x0, 0x0)
	github.com/weaveworks/eksctl/pkg/ctl/create/nodegroup.go:86 +0x106
github.com/spf13/cobra.(*Command).execute(0xc00054cf00, 0xc0008d9ee0, 0xd, 0xd, 0xc00054cf00, 0xc0008d9ee0)
	github.com/spf13/cobra@v1.2.1/command.go:856 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc00054c280, 0xc000205e40, 0x1, 0xc000b3ff70)
	github.com/spf13/cobra@v1.2.1/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
	github.com/weaveworks/eksctl/cmd/eksctl/main.go:77 +0x41b
```

**Anything else we need to know?**
After removing "--instance-selector-cpu-architecture arm64", the expected node group was created.
I think the panic is caused by using this option.

- What OS are you using?
  - macOS BigSur v11.5.1
- Are you using a downloaded binary or did you compile eksctl?
  - homebrew 

**Versions**

```
$ eksctl info
eksctl version: 0.60.0
kubectl version: v1.22.0
```
EKS Cluster version v1.21

**Comment by Callisto13** [comment]
Thanks for reporting @ohmakoto 👍 

If you want to submit a fix please go for it 😄  otherwise the team will look into it asap

**Comment by cPu1** [comment]
This was a regression that was fixed in the [last release](https://github.com/weaveworks/eksctl/releases/tag/0.61.0-rc.0). Can you try it and let us know if you're still facing the issue?

**Comment by Callisto13** [comment]
Oh yeh forgot I did that 😂

**Comment by ohmakoto** [comment]
Thanks for the quick reply!
I ran the same command on 0.61.0-rc.0 with only the node group name different.
No panic occurred, but I got an error message instead.
```
./eksctl version
0.61.0-rc.0

./eksctl create nodegroup \
--cluster LatestOcean \
--name AMZN-Linux2-arm64-2 \
--node-ami-family AmazonLinux2 \
--spot \
--instance-selector-cpu-architecture arm64 \
--instance-types t4g.medium,t4g.large,t4g.small
2021-08-10 17:29:15 [ℹ]  eksctl version 0.61.0-rc.0
2021-08-10 17:29:15 [ℹ]  using region ap-northeast-1
2021-08-10 17:29:15 [ℹ]  will use version 1.21 for new nodegroup(s) based on control plane version
Error: instance types matched by instance selector criteria do not match managedNodeGroup.instanceTypes.instanceTypes for nodegroup "AMZN-Linux2-arm64-2"; either remove instanceSelector or instanceTypes and retry the operation
```
I removed the "instance-types" and ran the command to try it out; no panic in Golang, but an error in Cloudformation instead.
```
./eksctl create nodegroup \
--cluster LatestOcean \
--name AMZN-Linux2-arm64-2 \
--node-ami-family AmazonLinux2 \
--spot \
--instance-selector-cpu-architecture arm64
2021-08-10 17:33:30 [ℹ]  eksctl version 0.61.0-rc.0
2021-08-10 17:33:30 [ℹ]  using region ap-northeast-1
2021-08-10 17:33:31 [ℹ]  will use version 1.21 for new nodegroup(s) based on control plane version
2021-08-10 17:33:40 [ℹ]  nodegroup "AMZN-Linux2-arm64-2" will use "" [AmazonLinux2/1.21]
2021-08-10 17:33:41 [ℹ]  3 existing nodegroup(s) (AMZN-Linux2-arm64,AMZN-Linux2-x86,Bottlerocket-x86) will be excluded
2021-08-10 17:33:41 [ℹ]  1 nodegroup (AMZN-Linux2-arm64-2) was included (based on the include/exclude rules)
2021-08-10 17:33:41 [ℹ]  will create a CloudFormation stack for each of 1 managed nodegroups in cluster "LatestOcean"
2021-08-10 17:33:43 [ℹ]  2 sequential tasks: { fix cluster compatibility, 1 task: { 1 task: { create managed nodegroup "AMZN-Linux2-arm64-2" } } }
2021-08-10 17:33:43 [ℹ]  checking cluster stack for missing resources
2021-08-10 17:33:43 [ℹ]  cluster stack has all required resources
2021-08-10 17:33:43 [ℹ]  building managed nodegroup stack "eksctl-LatestOcean-nodegroup-AMZN-Linux2-arm64-2"
2021-08-10 17:33:44 [ℹ]  deploying stack "eksctl-LatestOcean-nodegroup-AMZN-Linux2-arm64-2"
2021-08-10 17:33:44 [ℹ]  waiting for CloudFormation stack "eksctl-LatestOcean-nodegroup-AMZN-Linux2-arm64-2"
2021-08-10 17:34:00 [ℹ]  waiting for CloudFormation stack "eksctl-LatestOcean-nodegroup-AMZN-Linux2-arm64-2"
2021-08-10 17:34:18 [ℹ]  waiting for CloudFormation stack "eksctl-LatestOcean-nodegroup-AMZN-Linux2-arm64-2"
2021-08-10 17:34:39 [ℹ]  waiting for CloudFormation stack "eksctl-LatestOcean-nodegroup-AMZN-Linux2-arm64-2"
2021-08-10 17:34:57 [ℹ]  waiting for CloudFormation stack "eksctl-LatestOcean-nodegroup-AMZN-Linux2-arm64-2"
2021-08-10 17:34:58 [✖]  unexpected status "ROLLBACK_IN_PROGRESS" while waiting for CloudFormation stack "eksctl-LatestOcean-nodegroup-AMZN-Linux2-arm64-2"
2021-08-10 17:34:58 [ℹ]  fetching stack events in attempt to troubleshoot the root cause of the failure
2021-08-10 17:34:58 [!]  AWS::EC2::LaunchTemplate/LaunchTemplate: DELETE_IN_PROGRESS
2021-08-10 17:34:58 [!]  AWS::IAM::Role/NodeInstanceRole: DELETE_IN_PROGRESS
2021-08-10 17:34:58 [✖]  AWS::EKS::Nodegroup/ManagedNodeGroup: CREATE_FAILED – "Instance types list should not contain more than 40 instance types. (Service: AmazonEKS; Status Code: 400; Error Code: InvalidParameterException; Request ID: bda7cd7b-3d67-450d-8be4-b1194dff8fbc; Proxy: null)"
2021-08-10 17:34:58 [ℹ]  1 error(s) occurred and nodegroups haven't been created properly, you may wish to check CloudFormation console
2021-08-10 17:34:58 [ℹ]  to cleanup resources, run 'eksctl delete nodegroup --region=ap-northeast-1 --cluster=LatestOcean --name=<name>' for each of the failed nodegroup
2021-08-10 17:34:58 [✖]  waiting for CloudFormation stack "eksctl-LatestOcean-nodegroup-AMZN-Linux2-arm64-2": ResourceNotReady: failed waiting for successful resource state
Error: failed to create nodegroups for cluster "LatestOcean"
```

**Comment by ohmakoto** [comment]
I will only extract the Managed Node Group part from the Cloudformation template.
A lot of the latest Graviton2 instance types were specified.
```
"ManagedNodeGroup": {
      "Type": "AWS::EKS::Nodegroup",
      "Properties": {
        "AmiType": "AL2_ARM_64",
        "ClusterName": "LatestOcean",
        "InstanceTypes": [
          "c6g.12xlarge",
          "c6g.16xlarge",
          "c6g.2xlarge",
          "c6g.4xlarge",
          "c6g.8xlarge",
          "c6g.large",
          "c6g.medium",
          "c6g.metal",
          "c6g.xlarge",
          "c6gd.12xlarge",
          "c6gd.16xlarge",
          "c6gd.2xlarge",
          "c6gd.4xlarge",
          "c6gd.8xlarge",
          "c6gd.large",
          "c6gd.medium",
          "c6gd.metal",
          "c6gd.xlarge",
          "m6g.12xlarge",
          "m6g.16xlarge",
          "m6g.2xlarge",
          "m6g.4xlarge",
          "m6g.8xlarge",
          "m6g.large",
          "m6g.medium",
          "m6g.metal",
          "m6g.xlarge",
          "m6gd.12xlarge",
          "m6gd.16xlarge",
          "m6gd.2xlarge",
          "m6gd.4xlarge",
          "m6gd.8xlarge",
          "m6gd.large",
          "m6gd.medium",
          "m6gd.metal",
          "m6gd.xlarge",
          "r6g.12xlarge",
          "r6g.16xlarge",
          "r6g.2xlarge",
          "r6g.4xlarge",
          "r6g.8xlarge",
          "r6g.large",
          "r6g.medium",
          "r6g.metal",
          "r6g.xlarge",
          "r6gd.12xlarge",
          "r6gd.16xlarge",
          "r6gd.2xlarge",
          "r6gd.4xlarge",
          "r6gd.8xlarge",
          "r6gd.large",
          "r6gd.medium",
          "r6gd.metal",
          "r6gd.xlarge",
          "t4g.2xlarge",
          "t4g.large",
          "t4g.medium",
          "t4g.micro",
          "t4g.nano",
          "t4g.small",
          "t4g.xlarge"
        ],
        "CapacityType": "SPOT",
        "Labels": {
          "alpha.eksctl.io/cluster-name": "LatestOcean",
          "alpha.eksctl.io/nodegroup-name": "AMZN-Linux2-arm64-2"
        },
        "LaunchTemplate": {
          "Id": {
            "Ref": "LaunchTemplate"
          }
        },
        "NodeRole": {
          "Fn::GetAtt": [
            "NodeInstanceRole",
            "Arn"
          ]
        },
        "NodegroupName": "AMZN-Linux2-arm64-2",
        "ScalingConfig": {
          "DesiredSize": 2,
          "MaxSize": 2,
          "MinSize": 2
        },
        "Subnets": {
          "Fn::Split": [
            ",",
            {
              "Fn::ImportValue": "eksctl-LatestOcean-cluster::SubnetsPublic"
            }
          ]
        },
        "Tags": {
          "alpha.eksctl.io/nodegroup-name": "AMZN-Linux2-arm64-2",
          "alpha.eksctl.io/nodegroup-type": "managed"
        }
      }
    }
```

**Comment by ohmakoto** [comment]
I removed --instance-selector-cpu-architecture arm64 and ran it, and the cfn template only specified m5.large.
It seems to only happen with arm64 if you're using a lot of instance types.

**Comment by Callisto13** [comment]
👍  thanks for verifying that @ohmakoto .

@cPu1 this sounds familiar... did you say something about the selector returning too many instance the other day?

**Comment by cPu1** [comment]
> ./eksctl version
> 0.61.0-rc.0
> 
> ./eksctl create nodegroup \
> --cluster LatestOcean \
> --name AMZN-Linux2-arm64-2 \
> --node-ami-family AmazonLinux2 \
> --spot \
> --instance-selector-cpu-architecture arm64 \
> --instance-types t4g.medium,t4g.large,t4g.small
> 2021-08-10 17:29:15 [ℹ]  eksctl version 0.61.0-rc.0
> 2021-08-10 17:29:15 [ℹ]  using region ap-northeast-1
> 2021-08-10 17:29:15 [ℹ]  will use version 1.21 for new nodegroup(s) based on control plane version
> Error: instance types matched by instance selector criteria do not match managedNodeGroup.instanceTypes.instanceTypes for nodegroup "AMZN-Linux2-arm64-2"; either remove instanceSelector or instanceTypes and retry the operation


@ohmakoto, you cannot specify both `--instance-selector-*` options and `--instance-types` as the instances selected by the instance selector will end up overriding your supplied instance types. We'll address this issue by adding validation that disallows passing both options at the same time.

> ```
> 
> I removed the "instance-types" and ran the command to try it out; no panic in Golang, but an error in Cloudformation instead.
> 
> ```
> ./eksctl create nodegroup \
> --cluster LatestOcean \
> --name AMZN-Linux2-arm64-2 \
> --node-ami-family AmazonLinux2 \
> --spot \
> --instance-selector-cpu-architecture arm64


In this case, the validation failed at the API level because the instance selector criteria returned too many instances (more than 40), which the API does not allow. This can be fixed in eksctl by failing early if more than 40 instance types are returned, and ask users to provide a more narrow criteria so that fewer instance types are returned. 

In the meantime, can you try passing more instance selector options like `--instance-selector-vcpus=2` so that fewer instance types are returned?

**Comment by ohmakoto** [comment]
@cPu1 
Thanks for your comment!

> In the meantime, you can try passing more instance selector options like --instance-selector-vcpus=2 so that fewer instance types are returned.

When I used instance-selector-vcpus=2, I was indeed able to create a managed node group with an instance type of two vCPUs.
This option is so cool!
