### ISSUE TITLE
Panic getting nodegroup by name

### ISSUE THREAD

**Issue by artem-nefedov** [weaveworks/eksctl#4082]
eksctl panics when I try to call `get nodegroup` with `--name` flag:

```
➜ AWS_PROFILE=myprofile eksctl get nodegroup --region us-west-2 --cluster test-cluster-3 --name managed-ng-1
2021-08-12 15:11:42 [ℹ]  eksctl version 0.61.0-rc.1
2021-08-12 15:11:42 [ℹ]  using region us-west-2
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/weaveworks/eksctl/pkg/actions/nodegroup.(*Manager).Get(0xc000c90ea0, 0x7ffeefbff636, 0xc, 0xc000f318c0, 0xc000c90ea0, 0x0)
        github.com/weaveworks/eksctl/pkg/actions/nodegroup/get.go:129 +0x69a
github.com/weaveworks/eksctl/pkg/ctl/get.doGetNodeGroup(0xc0007378c0, 0xc000c5ef00, 0xc0005420a8, 0x0, 0x0)
        github.com/weaveworks/eksctl/pkg/ctl/get/nodegroup.go:95 +0x63b
github.com/weaveworks/eksctl/pkg/ctl/get.getNodeGroupCmd.func1(0xc000c5af00, 0xc0003ec360, 0x0, 0x6, 0x0, 0x0)
        github.com/weaveworks/eksctl/pkg/ctl/get/nodegroup.go:32 +0x9b
github.com/spf13/cobra.(*Command).execute(0xc000c5af00, 0xc0003ec300, 0x6, 0x6, 0xc000c5af00, 0xc0003ec300)
        github.com/spf13/cobra@v1.2.1/command.go:856 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc000b16a00, 0xc00070f320, 0x1, 0xc000d1ff70)
        github.com/spf13/cobra@v1.2.1/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
        github.com/weaveworks/eksctl/cmd/eksctl/main.go:77 +0x41b

```

At the same time, getting all nodegroups of the cluster works fine:

```
➜ AWS_PROFILE=myprofile eksctl get nodegroup --region us-west-2 --cluster test-cluster-3
2021-08-12 15:14:46 [ℹ]  eksctl version 0.61.0-rc.1
2021-08-12 15:14:46 [ℹ]  using region us-west-2
2021-08-12 15:14:51 [ℹ]  no instance types reported by EKS for nodegroup "managed-ng-1"
CLUSTER         NODEGROUP       STATUS          CREATED                 MIN SIZE        MAX SIZE        DESIRED CAPACITY        INSTANCE TYPE   IMAGE ID        ASG NAME
test-cluster-3  managed-ng-1    UPDATING        2021-08-12T10:34:40Z    2               10              2                       -               AL2_x86_64      eks-managed-ng-1-febd9cf6-cdc1-53a4-8155-4c6c7b2fbc68
```

Note that nodegroup is being upgraded when this happens.

Nodegroup has a custom launch template, and I have the following command running in a separate terminal:

```
AWS_PROFILE=myprofile eksctl upgrade nodegroup --cluster test-cluster-3 --region us-west-2 --name managed-ng-1 --kubernetes-version=1.21 --wait --launch-template-version='$Latest'
```

**Versions**

```
$ eksctl info
eksctl version: 0.61.0-rc.1
kubectl version: v1.21.3
OS: darwin
```

**Comment by cPu1** [comment]
Hi @artem-nefedov, looks like eksctl is using the `InstanceTypes` field from a `DescribeNodegroup` call but this field won't be present for nodegroups using a custom launch template. Can you share the output of ` aws eks describe-nodegroup --cluster-name test-cluster3 --nodegroup-name managed-ng-1`, redacting any information that you deem sensitive?

**Comment by artem-nefedov** [comment]
@cPu1 Here you go

```
{
    "nodegroup": {
        "nodegroupName": "managed-ng-1",
        "nodegroupArn": "arn:aws:eks:us-west-2:00000000000:nodegroup/test-cluster-3/managed-ng-1/febd9cf6-cdc1-53a4-8155-4c6c7b2fbc68",
        "clusterName": "test-cluster-3",
        "version": "1.21",
        "releaseVersion": "1.21.2-20210722",
        "createdAt": "2021-08-12T13:34:40.723000+03:00",
        "modifiedAt": "2021-08-12T15:34:34.428000+03:00",
        "status": "ACTIVE",
        "capacityType": "ON_DEMAND",
        "scalingConfig": {
            "minSize": 2,
            "maxSize": 10,
            "desiredSize": 2
        },
        "subnets": [
            "subnet-070856d6fdecedb9a",
            "subnet-0b36aa4958970d98c",
            "subnet-0be9c6829b452c338"
        ],
        "amiType": "AL2_x86_64",
        "nodeRole": "arn:aws:iam::00000000000:role/eksctl-test-cluster-3-nodegroup-m-NodeInstanceRole-1J4GFQ20T2KLA",
        "labels": {
            "alpha.eksctl.io/nodegroup-name": "managed-ng-1",
            "alpha.eksctl.io/cluster-name": "test-cluster-3"
        },
        "resources": {
            "autoScalingGroups": [
                {
                    "name": "eks-managed-ng-1-febd9cf6-cdc1-53a4-8155-4c6c7b2fbc68"
                }
            ]
        },
        "health": {
            "issues": []
        },
        "updateConfig": {
            "maxUnavailable": 1
        },
        "launchTemplate": {
            "name": "eks-managed-nodes-test-cluster-3",
            "version": "2",
            "id": "lt-0e6f464e730cfcf4e"
        },
        "tags": {
            "Role": "shared/eks/compute",
            "aws:cloudformation:stack-name": "eksctl-test-cluster-3-nodegroup-managed-ng-1",
            "Owner": "rnd/sw/peg/cs",
            "alpha.eksctl.io/cluster-name": "test-cluster-3",
            "alpha.eksctl.io/nodegroup-name": "managed-ng-1",
            "aws:cloudformation:stack-id": "arn:aws:cloudformation:us-west-2:00000000000:stack/eksctl-test-cluster-3-nodegroup-managed-ng-1/c6e6cb40-fb58-11eb-9bf2-0a23c6434ac1",
            "eksctl.cluster.k8s.io/v1alpha1/cluster-name": "test-cluster-3",
            "Environment": "test-cluster-3",
            "aws:cloudformation:logical-id": "ManagedNodeGroup",
            "alpha.eksctl.io/nodegroup-type": "managed",
            "Requestor": "rnd/sw/peg/cs",
            "alpha.eksctl.io/eksctl-version": "0.60.0"
        }
    }
}

```

**Comment by cPu1** [comment]
Thanks @artem-nefedov. eksctl should fetch the instance type from the associated launch template if a nodegroup was created with a custom launch template. We'll work on a fix soon.

**Comment by aclevername** [comment]
I've opened a PR to fix the panic https://github.com/weaveworks/eksctl/pull/4092



> Thanks @artem-nefedov. eksctl should fetch the instance type from the associated launch template if a nodegroup was created with a custom launch template. We'll work on a fix soon.

Working on this :smile:
