### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by davivcgarcia** [weaveworks/eksctl#4146]
**What were you trying to accomplish?**
The `eksctl` panics when trying to deploy a cluster with the `ssm.enableSsm` enabled.

**What happened?**
```
2021-08-28 03:08:10 [!]  SSM is now enabled by default; `ssh.enableSSM` is deprecated and will be removed in a future release
2021-08-28 03:08:10 [ℹ]  eksctl version 0.63.0
2021-08-28 03:08:10 [ℹ]  using region us-east-1
2021-08-28 03:08:10 [ℹ]  subnets for us-east-1a - public:192.168.0.0/19 private:192.168.96.0/19
2021-08-28 03:08:10 [ℹ]  subnets for us-east-1b - public:192.168.32.0/19 private:192.168.128.0/19
2021-08-28 03:08:10 [ℹ]  subnets for us-east-1c - public:192.168.64.0/19 private:192.168.160.0/19
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x27097ae]

goroutine 1 [running]:
github.com/weaveworks/eksctl/pkg/ctl/create.doCreateCluster(0xc000622790, 0xc00007dc00, 0xc0005bdb80, 0x0, 0x0)
        github.com/weaveworks/eksctl/pkg/ctl/create/cluster.go:198 +0x60e
github.com/weaveworks/eksctl/pkg/ctl/create.createClusterCmd.func1(0xc000622790, 0xc00007dc00, 0xc0005bdb80, 0xc0005bdb80, 0x3889240)
        github.com/weaveworks/eksctl/pkg/ctl/create/cluster.go:37 +0x3f
github.com/weaveworks/eksctl/pkg/ctl/create.createClusterCmdWithRunFunc.func1(0xc00055d400, 0xc00007da00, 0x0, 0x2, 0x0, 0x0)
        github.com/weaveworks/eksctl/pkg/ctl/create/cluster.go:56 +0x12c
github.com/spf13/cobra.(*Command).execute(0xc00055d400, 0xc00007d9e0, 0x2, 0x2, 0xc00055d400, 0xc00007d9e0)
        github.com/spf13/cobra@v1.2.1/command.go:856 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc00055c000, 0xc0001f3760, 0x1, 0xc0008dff70)
        github.com/spf13/cobra@v1.2.1/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
        github.com/weaveworks/eksctl/cmd/eksctl/main.go:77 +0x41b
```

**How to reproduce it?**

 1. Create a cluster with `eksctl create cluster -f` with the following configuration:

```yaml
kind: ClusterConfig
apiVersion: eksctl.io/v1alpha5
metadata:
  name: sandbox
  version: "1.21"
  region: us-east-1
availabilityZones:
  - us-east-1a
  - us-east-1b
  - us-east-1c
addons:
  - name: vpc-cni
    version: latest
  - name: kube-proxy
    version: latest
  - name: coredns
    version: latest
managedNodeGroups:
  - name: sandbox-amd64-workers
    instanceType: m5.large
    desiredCapacity: 3
    minSize: 2
    maxSize: 5
    privateNetworking: true
    ssh:
      enableSsm: true
```

**Anything else we need to know?**

```
$ uname -a
Linux ip-172-31-4-200.ec2.internal 4.14.243-185.433.amzn2.x86_64 #1 SMP Mon Aug 9 05:55:52 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Versions**
```
$ eksctl info
eksctl version: 0.63.0
kubectl version: v1.21.2-13+d2965f0db10712
OS: linux
```

**Comment by erankitcs** [comment]
Thanks for raising the issue @davivcgarcia. I am also facing a similar issue.

**Comment by cPu1** [comment]
Thanks for opening an issue, we're working on a fix. In the meantime, you can work around this by removing the `ssh.enableSsm` field from your ClusterConfig as that's the default behaviour now.

**Comment by cPu1** [comment]
The fix is out in https://github.com/weaveworks/eksctl/releases/tag/v0.64.0-rc.3
