### ISSUE TITLE
eksctl create iamserviceaccount crashes

### ISSUE THREAD

**Issue by runningman84** [weaveworks/eksctl#4153]
**What were you trying to accomplish?**

I want to add additional iam service account using the _eksctl create iamserviceaccount_ command

**What happened?**

eksctl crashes

**How to reproduce it?**

use eksctl 0.63.0 to create service accounts in an existing cluster

**Logs**

```
$ eksctl create iamserviceaccount -f cluster-config/dev.yaml
2021-08-30 13:10:39 [!]  SSM is now enabled by default; `ssh.enableSSM` is deprecated and will be removed in a future release
2021-08-30 13:10:39 [ℹ]  eksctl version 0.63.0
2021-08-30 13:10:39 [ℹ]  using region eu-central-1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x2a304f8]

goroutine 1 [running]:
github.com/weaveworks/eksctl/pkg/eks.(*ClusterProvider).clusterInfoNeedsUpdate(...)
	/private/tmp/eksctl-20210827-67620-tneh3z/pkg/eks/cache.go:17
github.com/weaveworks/eksctl/pkg/eks.(*ClusterProvider).maybeRefreshClusterStatus(0x1, 0x0)
	/private/tmp/eksctl-20210827-67620-tneh3z/pkg/eks/eks.go:173 +0x18
github.com/weaveworks/eksctl/pkg/eks.(*ClusterProvider).CanOperate(0x0, 0xc000582e00)
	/private/tmp/eksctl-20210827-67620-tneh3z/pkg/eks/eks.go:195 +0x2d
github.com/weaveworks/eksctl/pkg/ctl/create.doCreateIAMServiceAccount(0xc0005bc000, 0x0)
	/private/tmp/eksctl-20210827-67620-tneh3z/pkg/ctl/create/iamserviceaccount.go:86 +0xbc
github.com/weaveworks/eksctl/pkg/ctl/create.createIAMServiceAccountCmd.func1(0xc00043f6e0, 0x80)
	/private/tmp/eksctl-20210827-67620-tneh3z/pkg/ctl/create/iamserviceaccount.go:20 +0x19
github.com/weaveworks/eksctl/pkg/ctl/create.createIAMServiceAccountCmdWithRunFunc.func1(0xc000204780, {0xc00043f6e0, 0x2, 0x2})
	/private/tmp/eksctl-20210827-67620-tneh3z/pkg/ctl/create/iamserviceaccount.go:41 +0x7f
github.com/spf13/cobra.(*Command).execute(0xc000204780, {0xc00043f6c0, 0x2, 0x2})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003eb680)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
	/private/tmp/eksctl-20210827-67620-tneh3z/cmd/eksctl/main.go:77 +0x3a5
```

**Anything else we need to know?**

**Versions**

```
$ eksctl info
eksctl version: 0.63.0
kubectl version: v1.22.1
OS: darwin
```

**Comment by cPu1** [comment]
This issue has been addressed and a fix will be out today: https://github.com/weaveworks/eksctl/issues/4146#issuecomment-908130849

In the meantime, you can work around this by removing `ssm.enableSsm` from your ClusterConfig.

**Comment by cPu1** [comment]
The fix is out in https://github.com/weaveworks/eksctl/releases/tag/v0.64.0-rc.3

**Comment by runningman84** [comment]
I have commented out the ssh part but still got the same error...

**Comment by cPu1** [comment]
> I have commented out the ssh part but still got the same error...

Can you share your ClusterConfig?
