### ISSUE TITLE
panic in addArm64NodeSelector when upgrading kube-proxy

### ISSUE THREAD

**Issue by jack-evans** [weaveworks/eksctl#4245]
**What were you trying to accomplish?**

I was attempting to upgrade the kube-proxy component in my aws cluster by running `eksctl utils upgrade-kube-proxy --cluster ....`

**What happened?**

I get the following output:

```
2021-09-23 16:28:01 [ℹ]  eksctl version 0.67.0
2021-09-23 16:28:01 [ℹ]  using region us-east-1
2021-09-23 16:28:02 [ℹ]  missing arm64 nodeSelector value
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x29f4c55]

goroutine 1 [running]:
github.com/weaveworks/eksctl/pkg/addons/default.addArm64NodeSelector(0xc000fa09a0, {0x3aca9c6, 0x3ae9f67})
	github.com/weaveworks/eksctl/pkg/addons/default/kube_proxy.go:153 +0x35
github.com/weaveworks/eksctl/pkg/addons/default.UpdateKubeProxy({0x4013e10, 0xc000f2e000}, {0xc000267cf0, 0x7}, 0x0)
	github.com/weaveworks/eksctl/pkg/addons/default/kube_proxy.go:122 +0x594
github.com/weaveworks/eksctl/pkg/ctl/utils.doUpdateKubeProxy(0xc000534210)
	github.com/weaveworks/eksctl/pkg/ctl/utils/update_kube_proxy.go:62 +0x12c
github.com/weaveworks/eksctl/pkg/ctl/utils.updateKubeProxyCmd.func1(0xc00015a280, {0xc0007ba7e0, 0x7, 0x7})
	github.com/weaveworks/eksctl/pkg/ctl/utils/update_kube_proxy.go:20 +0x59
github.com/spf13/cobra.(*Command).execute(0xc00015a280, {0xc0007ba770, 0x7, 0x7})
	github.com/spf13/cobra@v1.2.1/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc0005c8c80)
	github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
	github.com/weaveworks/eksctl/cmd/eksctl/main.go:99 +0x525
```

It appears to be coming from [here](https://github.com/weaveworks/eksctl/blob/main/pkg/addons/default/kube_proxy.go#L153-L161).

**How to reproduce it?**

Have the following kube-proxy daemonset running on your cluster:
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "10"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"DaemonSet","metadata":{"annotations":{},"labels":{"eks.amazonaws.com/component":"kube-proxy","k8s-app":"kube-proxy"},"name":"kube-proxy","namespace":"kube-system"},"spec":{"selector":{"matchLabels":{"k8s-app":"kube-proxy"}},"template":{"metadata":{"annotations":{"scheduler.alpha.kubernetes.io/critical-pod":""},"labels":{"k8s-app":"kube-proxy"}},"spec":{"containers":[{"command":["/bin/sh","-c","kube-proxy --resource-container=\"\" --oom-score-adj=-998 --master=https://59eba41dbb3e69921e4d0af76b2814ee.yl4.us-east-1.eks.amazonaws.com --kubeconfig=/var/lib/kube-proxy/kubeconfig --proxy-mode=iptables --v=2 1\u003e\u003e/var/log/kube-proxy.log 2\u003e\u00261"],"image":"602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/kube-proxy:v1.10.3","name":"kube-proxy","resources":{"requests":{"cpu":"100m"}},"securityContext":{"privileged":true},"volumeMounts":[{"mountPath":"/var/log","name":"varlog","readOnly":false},{"mountPath":"/run/xtables.lock","name":"xtables-lock","readOnly":false},{"mountPath":"/var/lib/kube-proxy/","name":"kubeconfig"}]}],"hostNetwork":true,"serviceAccountName":"kube-proxy","tolerations":[{"effect":"NoExecute","operator":"Exists"},{"effect":"NoSchedule","operator":"Exists"}],"volumes":[{"hostPath":{"path":"/var/log"},"name":"varlog"},{"hostPath":{"path":"/run/xtables.lock","type":"FileOrCreate"},"name":"xtables-lock"},{"configMap":{"name":"kube-proxy"},"name":"kubeconfig"}]}},"updateStrategy":{"rollingUpdate":{"maxUnavailable":"10%"},"type":"RollingUpdate"}}}
  creationTimestamp: "2018-08-29T12:55:10Z"
  generation: 10
  labels:
    eks.amazonaws.com/component: kube-proxy
    k8s-app: kube-proxy
  name: kube-proxy
  namespace: kube-system
  resourceVersion: "196859403"
  selfLink: /apis/apps/v1/namespaces/kube-system/daemonsets/kube-proxy
  uid: c339a828-ab8a-11e8-a044-12c352781cb6
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: kube-proxy
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      creationTimestamp: null
      labels:
        k8s-app: kube-proxy
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - kube-proxy --resource-container="" --oom-score-adj=-998 --master=https://59eba41dbb3e69921e4d0af76b2814ee.yl4.us-east-1.eks.amazonaws.com
          --kubeconfig=/var/lib/kube-proxy/kubeconfig --proxy-mode=iptables --v=2
          1>>/var/log/kube-proxy.log 2>&1
        image: 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/kube-proxy:v1.15.11
        imagePullPolicy: IfNotPresent
        name: kube-proxy
        resources:
          requests:
            cpu: 100m
        securityContext:
          privileged: true
          procMount: Default
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/log
          name: varlog
        - mountPath: /run/xtables.lock
          name: xtables-lock
        - mountPath: /var/lib/kube-proxy/
          name: kubeconfig
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: kube-proxy
      serviceAccountName: kube-proxy
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoExecute
        operator: Exists
      - effect: NoSchedule
        operator: Exists
      volumes:
      - hostPath:
          path: /var/log
          type: ""
        name: varlog
      - hostPath:
          path: /run/xtables.lock
          type: FileOrCreate
        name: xtables-lock
      - configMap:
          defaultMode: 420
          name: kube-proxy
        name: kubeconfig
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 10%
    type: RollingUpdate
status:
  currentNumberScheduled: 3
  desiredNumberScheduled: 3
  numberAvailable: 3
  numberMisscheduled: 0
  numberReady: 3
  observedGeneration: 10
  updatedNumberScheduled: 3
```

attempt to run `eksctl utils upgrade-kube-proxy --cluster ...` and see the error 

**Logs**

**Anything else we need to know?**

darwin
downloaded binary
profile

**Versions**

```
$ eksctl info
eksctl version: 0.67.0
kubectl version: v1.21.4
OS: darwin
```

**Comment by jack-evans** [comment]
I guess a follow on question from my end, it checks for arm64, yet my nodes are amd64, shouldn't this be dependant on node arch? 

I am happy to put a PR together to fix this, however I was wondering the route you would want to go down... do we want to create that structure if it doesn't exist or do we not touch it at all if nil?

**Comment by aclevername** [comment]
Thanks for opening the issue @jack-evans . What kubernetes version is your cluster? Are you running this after upgrading your cluster?

**Comment by jack-evans** [comment]
@aclevername AWS kubernetes cluster is 1.19. Tbh, I think this is a case of our bad upgrade documented process (hence trying to move to eksctl), where parts were not followed properly so we've ended up with a kube-proxy version that is much older than it should be. For example, the same cluster was still running kubedns which hasnt been part of EKS clusters since 1.10.

Looking at https://docs.aws.amazon.com/eks/latest/userguide/managing-kube-proxy.html, it looks like our kube-proxy component hasn't been upgraded since about Kubernetes 1.15.... Luckily its just a dev cluster 😄

**Comment by aclevername** [comment]
> @aclevername AWS kubernetes cluster is 1.19. Tbh, I think this is a case of our bad upgrade documented process (hence trying to move to eksctl), where parts were not followed properly so we've ended up with a kube-proxy version that is much older than it should be. For example, the same cluster was still running kubedns which hasnt been part of EKS clusters since 1.10.

:+1: 

> Looking at https://docs.aws.amazon.com/eks/latest/userguide/managing-kube-proxy.html, it looks like our kube-proxy component hasn't been upgraded since about Kubernetes 1.15.... Luckily its just a dev cluster

Have you considered switching to EKS managed addons? 
https://aws.amazon.com/blogs/containers/introducing-amazon-eks-add-ons/
https://eksctl.io/usage/addons/

It appears its compatible with `arm64` nodes:
```
eksctl utils describe-addon-versions --name kube-proxy --kubernetes-version 1.19
2021-09-24 09:48:48 [ℹ]  describing addon versions for addon: kube-proxy
{
  Addons: [{
      AddonName: "kube-proxy",
      AddonVersions: [{
          AddonVersion: "v1.19.6-eksbuild.2",
          Architecture: ["amd64","arm64"],
          Compatibilities: [{
              ClusterVersion: "1.19",
              DefaultVersion: true,
              PlatformVersions: ["eks.4+"]
            }]
        },{
          AddonVersion: "v1.18.8-eksbuild.1",
          Architecture: ["amd64","arm64"],
          Compatibilities: [{
              ClusterVersion: "1.19",
              DefaultVersion: false,
              PlatformVersions: ["eks.4+"]
            }]
        }],
      Type: "networking"
    }]
}
```

**Comment by jack-evans** [comment]
> > @aclevername AWS kubernetes cluster is 1.19. Tbh, I think this is a case of our bad upgrade documented process (hence trying to move to eksctl), where parts were not followed properly so we've ended up with a kube-proxy version that is much older than it should be. For example, the same cluster was still running kubedns which hasnt been part of EKS clusters since 1.10.
> 
> 👍
> 
> > Looking at https://docs.aws.amazon.com/eks/latest/userguide/managing-kube-proxy.html, it looks like our kube-proxy component hasn't been upgraded since about Kubernetes 1.15.... Luckily its just a dev cluster
> 
> Have you considered switching to EKS managed addons?
> https://aws.amazon.com/blogs/containers/introducing-amazon-eks-add-ons/
> https://eksctl.io/usage/addons/
> 
> It appears its compatible with `arm64` nodes:
> 
> ```
> eksctl utils describe-addon-versions --name kube-proxy --kubernetes-version 1.19
> 2021-09-24 09:48:48 [ℹ]  describing addon versions for addon: kube-proxy
> {
>   Addons: [{
>       AddonName: "kube-proxy",
>       AddonVersions: [{
>           AddonVersion: "v1.19.6-eksbuild.2",
>           Architecture: ["amd64","arm64"],
>           Compatibilities: [{
>               ClusterVersion: "1.19",
>               DefaultVersion: true,
>               PlatformVersions: ["eks.4+"]
>             }]
>         },{
>           AddonVersion: "v1.18.8-eksbuild.1",
>           Architecture: ["amd64","arm64"],
>           Compatibilities: [{
>               ClusterVersion: "1.19",
>               DefaultVersion: false,
>               PlatformVersions: ["eks.4+"]
>             }]
>         }],
>       Type: "networking"
>     }]
> }
> ```

To get around this I think we should be able to upgrade to a new-ish version manually and then use eksctl or edit the daemonset to create the node affinity such that it does not panic. Out of curiosity what is the benefit of using addons? it seems like you still have to manage the upgrade lifecycle etc of them when updating/upgrading a cluster

**Comment by aclevername** [comment]
> To get around this I think we should be able to upgrade to a new-ish version manually and then use eksctl or edit the daemonset to create the node affinity such that it does not panic.

:+1: 

> Out of curiosity what is the benefit of using addons? it seems like you still have to manage the upgrade lifecycle etc of them when updating/upgrading a cluster

Its just a much cleaner interface than what `eksctl utils update-kube-proxy` does. You can see in the EKS console your addons & versions, also via the cli `eksctl get addons`. It also makes sure that if someone accidentally deletes the `kube-proxy` resources that they get restored back in.

**Comment by cPu1** [comment]
> This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 5 days.

Not stale, there's an open [PR](https://github.com/weaveworks/eksctl/pull/4254) that will fix this issue.
