### ISSUE TITLE
Karpenter fails installation with Fargate and/or with `createServiceAccount: true`

### ISSUE THREAD

**Issue by Skarlso** [weaveworks/eksctl#4528]
For more detail check the discussion here: https://github.com/weaveworks/eksctl/pull/4488#issuecomment-989288498

**Comment by Skarlso** [comment]
The service account is fixed. In terms of fargate:

```
2021-12-09T15:55:22.860Z        INFO    Successfully created the logger.
2021-12-09T15:55:22.860Z        INFO    Logging level set to: info
{"level":"info","ts":1639065322.96602,"logger":"fallback","caller":"injection/injection.go:61","msg":"Starting informers..."}
panic: Failed to call the metadata server's region API, EC2MetadataRequestError: failed to get EC2 instance identity document
caused by: RequestError: send request failed
caused by: Get "http://169.254.169.254/latest/dynamic/instance-identity/document": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

goroutine 1 [running]:
github.com/aws/karpenter/pkg/cloudprovider/aws.getRegionFromIMDS(0x0)
        github.com/aws/karpenter/pkg/cloudprovider/aws/cloudprovider.go:98 +0xab
github.com/aws/karpenter/pkg/cloudprovider/aws.NewCloudProvider({0x2630418, 0xc00063de00}, {0x1ee6ca0})
        github.com/aws/karpenter/pkg/cloudprovider/aws/cloudprovider.go:74 +0x1b5
github.com/aws/karpenter/pkg/cloudprovider/registry.newCloudProvider(...)
        github.com/aws/karpenter/pkg/cloudprovider/registry/aws.go:27
github.com/aws/karpenter/pkg/cloudprovider/registry.NewCloudProvider({0x2630418, 0xc00063de00}, {0x1ee6ca0})
        github.com/aws/karpenter/pkg/cloudprovider/registry/register.go:25 +0x28
main.main()
        github.com/aws/karpenter/cmd/controller/main.go:76 +0x2c5
```

**Comment by Skarlso** [comment]
@rothgar looks like Karpenter can't reach the AWS service endpoint in case of fargate. This is the whole config I used:

```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: test-karpenter-sa-4
  region: us-west-2
  version: '1.21'
karpenter:
  version: '0.5.1'
  createServiceAccount: true
fargateProfiles:
  - name: karpenter
    selectors:
    - namespace: karpenter
```

**Comment by Skarlso** [comment]
```
➜  karpenter-stack k get nodes
NAME                                                    STATUS   ROLES    AGE   VERSION
fargate-ip-192-168-160-20.us-west-2.compute.internal    Ready    <none>   10m   v1.21.2-eks-06eac09
fargate-ip-192-168-165-219.us-west-2.compute.internal   Ready    <none>   10m   v1.21.2-eks-06eac09
```

I have nodes.

**Comment by rothgar** [comment]
I'm trying a cluster right now including those namespaces

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: test-karpenter-sa-4
  region: us-west-2
  version: '1.21'
karpenter:
  version: '0.5.1'
  createServiceAccount: true
fargateProfiles:
  - name: karpenter
    selectors:
    - namespace: karpenter
    - namespace: kube-system
    - namespace: default
```

**Comment by Skarlso** [comment]
Yeah it still fails. :/ Can't reach the AWS endpoint. Maybe some Fargate permission is missing?

**Comment by Skarlso** [comment]
I just tried running it with those values:

```
2021-12-09T16:45:39.617Z    INFO    Successfully created the logger.                                                                 │
│ 2021-12-09T16:45:39.617Z    INFO    Logging level set to: info                                                                       │
│ {"level":"info","ts":1639068339.7223825,"logger":"fallback","caller":"injection/injection.go:61","msg":"Starting informers..."}      │
│ panic: Failed to call the metadata server's region API, EC2MetadataRequestError: failed to get EC2 instance identity document        │
│ caused by: RequestError: send request failed                                                                                         │
│ caused by: Get "http://169.254.169.254/latest/dynamic/instance-identity/document": context deadline exceeded (Client.Timeout exceede │
│                                                                                                                                      │
│ goroutine 1 :                                                                                                                        │
│ github.com/aws/karpenter/pkg/cloudprovider/aws.getRegionFromIMDS(0x0)                                                                │
│     github.com/aws/karpenter/pkg/cloudprovider/aws/cloudprovider.go:98 +0xab                                                         │
│ github.com/aws/karpenter/pkg/cloudprovider/aws.NewCloudProvider({0x2630418, 0xc0006b5cb0}, {0x1ee6ca0})                              │
│     github.com/aws/karpenter/pkg/cloudprovider/aws/cloudprovider.go:74 +0x1b5                                                        │
│ github.com/aws/karpenter/pkg/cloudprovider/registry.newCloudProvider(...)                                                            │
│     github.com/aws/karpenter/pkg/cloudprovider/registry/aws.go:27                                                                    │
│ github.com/aws/karpenter/pkg/cloudprovider/registry.NewCloudProvider({0x2630418, 0xc0006b5cb0}, {0x1ee6ca0})                         │
│     github.com/aws/karpenter/pkg/cloudprovider/registry/register.go:25 +0x28                                                         │
│ main.main()                                                                                                                          │
│     github.com/aws/karpenter/cmd/controller/main.go:76 +0x2c5 
```

Still getting the error.

**Comment by rothgar** [comment]
My assumption is we also need to enable oidc. I didn't see that in the examples and I wasn't sure if we were doing that automatically. The service account will require it

**Comment by Skarlso** [comment]
Ah, yeah, good point. No, we aren't enabling it automatically. And yeah, I think that also might be a bug because I'm not using oidc when the service account creates. 🤔

**Comment by rothgar** [comment]
I'm trying right now with
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: karpenter-2
  region: us-east-1
  version: '1.21'
iam:
  withOIDC: true
karpenter:
  version: '0.5.1'
  createServiceAccount: true
fargateProfiles:
  - name: karpenter
    selectors:
    - namespace: karpenter
    - namespace: kube-system
    - namespace: default
```

**Comment by rothgar** [comment]
If we use fargate we'll also need to tell the helm chart not to create the namespace

```
2021-12-09 09:08:11 [ℹ]  1 error(s) occurred while installing Karpenter, you may wish to check your Cluster for further information
2021-12-09 09:08:11 [✖]  failed to install Karpenter chart: failed to install chart: rendered manifests contain a resource that already exists. Unable to continue with install: ServiceAccount "karpenter" in namespace "karpenter" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: key "app.kubernetes.io/managed-by" must equal "Helm": current value is "eksctl"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "karpenter"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "karpenter"
Error: failed to install Karpenter: failed to install Karpenter on cluster
```

**Comment by Skarlso** [comment]
@rothgar Ah, so, if fargateProfiles is set oidc must be provided. That's only true for fargate though if I understand correctly?
And with fargate, don't create the namespace. Okay, I just set `	client.CreateNamespace = true` to false in case of fargate. Cool, this is awesome testing :)

**Comment by rothgar** [comment]
I _thought_ oidc was required for ec2 instances too for the service account to work (maybe it uses ec2 iam roles by default). Fargate for sure needs IAM attached to the SA/pod

With the fargate profile the namespace is automatically created in Kubernetes so the helm chart shouldn't try to create it.

Is there a new branch/build I should try?

**Comment by Skarlso** [comment]
I'm in GMT+1 so I'll be working on this tomorrow. :)

**Comment by Skarlso** [comment]
Actually, since I'm here and it's quit easy, give me a second, I'll update this pr: https://github.com/weaveworks/eksctl/pull/4531

**Comment by Skarlso** [comment]
@rothgar I updated https://github.com/weaveworks/eksctl/pull/4531. So you can pull that and try it.

Please note that I only updated the fargate thing. I'll work on OIDC tomorrow to make it a proper thing. :)

**Comment by Skarlso** [comment]
This has been addressed.
