### ISSUE TITLE
Karpenter test fails intermittently

### ISSUE THREAD

**Issue by Skarlso** [weaveworks/eksctl#4691]
Failed in a past couple runs.

**Comment by aclevername** [comment]
With `wait=false` for the helm install the test passes. But the controller starts to fail shortly after:
```
karpenter-controller-777cd6bd6c-vwqsn   0/1     CrashLoopBackOff   1          31s


2022-01-26T14:47:19.983Z        INFO    controller.controller.Termination       Starting Controller     {"commit": "dc47849", "reconciler group": "", "reconciler kind": "Node"}
2022-01-26T14:47:19.983Z        INFO    controller.controller.Termination       Starting workers        {"commit": "dc47849", "reconciler group": "", "reconciler kind": "Node", "worker count": 10}
E0126 14:47:19.984251       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 387 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1dc5800, 0x37a1200})
        k8s.io/apimachinery@v0.20.7/pkg/util/runtime/runtime.go:74 +0x85
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x0})
        k8s.io/apimachinery@v0.20.7/pkg/util/runtime/runtime.go:48 +0x75
panic({0x1dc5800, 0x37a1200})
        runtime/panic.go:1038 +0x215
github.com/awslabs/karpenter/pkg/cloudprovider/aws/apis/v1alpha1.Deserialize(0xc00071ce18)
        github.com/awslabs/karpenter/pkg/cloudprovider/aws/apis/v1alpha1/provider.go:55 +0x96
github.com/awslabs/karpenter/pkg/cloudprovider/aws.(*CloudProvider).GetInstanceTypes(0xc000686fa0, {0x250b3d8, 0xc0007601e0}, 0xa00000000)
        github.com/awslabs/karpenter/pkg/cloudprovider/aws/cloudprovider.go:136 +0x2f
github.com/awslabs/karpenter/pkg/controllers/metrics.(*Controller).updateNodeCounts(0xc000a35ba0, {0x250b3d8, 0xc0007601e0}, 0xc00071cd00)
        github.com/awslabs/karpenter/pkg/controllers/metrics/controller.go:101 +0x65
github.com/awslabs/karpenter/pkg/controllers/metrics.(*Controller).updateCounts.func1(0x0)
        github.com/awslabs/karpenter/pkg/controllers/metrics/controller.go:94 +0x57
k8s.io/client-go/util/workqueue.ParallelizeUntil.func1()
        k8s.io/client-go@v0.20.7/util/workqueue/parallelizer.go:90 +0x150
created by k8s.io/client-go/util/workqueue.ParallelizeUntil
        k8s.io/client-go@v0.20.7/util/workqueue/parallelizer.go:76 +0x1dc
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x16d1f76]

goroutine 387 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x0})
        k8s.io/apimachinery@v0.20.7/pkg/util/runtime/runtime.go:55 +0xd8
panic({0x1dc5800, 0x37a1200})
        runtime/panic.go:1038 +0x215
github.com/awslabs/karpenter/pkg/cloudprovider/aws/apis/v1alpha1.Deserialize(0xc00071ce18)
        github.com/awslabs/karpenter/pkg/cloudprovider/aws/apis/v1alpha1/provider.go:55 +0x96
github.com/awslabs/karpenter/pkg/cloudprovider/aws.(*CloudProvider).GetInstanceTypes(0xc000686fa0, {0x250b3d8, 0xc0007601e0}, 0xa00000000)
        github.com/awslabs/karpenter/pkg/cloudprovider/aws/cloudprovider.go:136 +0x2f
github.com/awslabs/karpenter/pkg/controllers/metrics.(*Controller).updateNodeCounts(0xc000a35ba0, {0x250b3d8, 0xc0007601e0}, 0xc00071cd00)
        github.com/awslabs/karpenter/pkg/controllers/metrics/controller.go:101 +0x65
github.com/awslabs/karpenter/pkg/controllers/metrics.(*Controller).updateCounts.func1(0x0)
        github.com/awslabs/karpenter/pkg/controllers/metrics/controller.go:94 +0x57
k8s.io/client-go/util/workqueue.ParallelizeUntil.func1()
        k8s.io/client-go@v0.20.7/util/workqueue/parallelizer.go:90 +0x150
created by k8s.io/client-go/util/workqueue.ParallelizeUntil
        k8s.io/client-go@v0.20.7/util/workqueue/parallelizer.go:76 +0x1dc

**Comment by Skarlso** [comment]
It's a bit disconcerting that this error only occurred with `--wait` removed from the HelmInstall.. Makes me wonder if we should disable it for good. 🤔
