### ISSUE TITLE
Crashed with delete cluster using config-file.

### ISSUE THREAD

**Issue by tanvp112** [weaveworks/eksctl#5377]
The program (version 0.100.0) crashed when delete cluster with [config-file](https://eksctl.io/usage/fargate-support/#creating-a-cluster-with-fargate-support-using-a-config-file):

```
$ eksctl delete cluster -f eksctl-fargate-only.yaml -w
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x26a6259]

goroutine 1 [running]:
github.com/weaveworks/eksctl/pkg/apis/eksctl.io/v1alpha5.noAccess(...)
        github.com/weaveworks/eksctl/pkg/apis/eksctl.io/v1alpha5/validation.go:442
github.com/weaveworks/eksctl/pkg/apis/eksctl.io/v1alpha5.(*ClusterConfig).ValidateClusterEndpointConfig(0xc000ae99e0?)
        github.com/weaveworks/eksctl/pkg/apis/eksctl.io/v1alpha5/validation.go:357 +0x39
github.com/weaveworks/eksctl/pkg/apis/eksctl.io/v1alpha5.(*ClusterConfig).ValidateVPCConfig(0xc000974fc0)
        github.com/weaveworks/eksctl/pkg/apis/eksctl.io/v1alpha5/validation.go:216 +0x45
github.com/weaveworks/eksctl/pkg/apis/eksctl.io/v1alpha5.ValidateClusterConfig(0xc000974fc0)
        github.com/weaveworks/eksctl/pkg/apis/eksctl.io/v1alpha5/validation.go:135 +0x6e5
github.com/weaveworks/eksctl/pkg/ctl/cmdutils.(*Cmd).NewCtl(0xc0001bfef0)
        github.com/weaveworks/eksctl/pkg/ctl/cmdutils/cmd.go:37 +0x4b
github.com/weaveworks/eksctl/pkg/ctl/cmdutils.(*Cmd).NewProviderForExistingCluster(0xc0001bfef0, {0x53ad658, 0xc00013c000})
        github.com/weaveworks/eksctl/pkg/ctl/cmdutils/cmd.go:78 +0x28
github.com/weaveworks/eksctl/pkg/ctl/delete.doDeleteCluster(0xc0001bfef0, 0x0, 0xfc?, 0x5a6825?, 0xc000b79c00?)
        github.com/weaveworks/eksctl/pkg/ctl/delete/cluster.go:69 +0xe7
github.com/weaveworks/eksctl/pkg/ctl/delete.deleteClusterCmd.func1(0xc0008c4030?, 0x0?, 0x9c?, 0xc000dffcd8?, 0xc000dffcd8?)
        github.com/weaveworks/eksctl/pkg/ctl/delete/cluster.go:20 +0x19
github.com/weaveworks/eksctl/pkg/ctl/delete.deleteClusterWithRunFunc.func1(0xc000b77900?, {0xc0008c4030?, 0x3?, 0x3?})
        github.com/weaveworks/eksctl/pkg/ctl/delete/cluster.go:38 +0xb9
github.com/spf13/cobra.(*Command).execute(0xc000b77900, {0xc0008c4000, 0x3, 0x3})
        github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0009c0280)
        github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
        github.com/weaveworks/eksctl/cmd/eksctl/main.go:102 +0x5db
```

**Comment by cPu1** [comment]
Thanks for the detailed issue. We'll look into this with priority.

**Comment by Himangini** [comment]
Hey @tanvp112 thanks for reporting the issue. Can you provide us the following info 



**Versions**

```
$ eksctl info
```

**Comment by Himangini** [comment]
I just created and deleted the cluster with the [Fargate example](https://eksctl.io/usage/fargate-support/#creating-a-cluster-with-fargate-support-using-a-config-file) mentioned in the docs and I didn't get any errors with latest eksctl version. Both commands ran without errors.

**Comment by tanvp112** [comment]
Hi @cPu1, v0.99.0 works using the same spec.

Hi @Himangini, I use pre-built binary on GitHub release:

```
$ eksctl info
eksctl version: 0.100.0
kubectl version: v1.22.9
OS: linux
```

Over my side `eksctl create cluster -f ` works as expected. Currently I am doing `eksctl delete cluster -r <region> -n <cluster> -w` as workaround. Will try to get more info and update.

**Comment by cPu1** [comment]
@tanvp112, thanks for the update. I did suspect that your ClusterConfig must've had `vpc.clusterEndpoints` defined as well. We'll try to reproduce this and work on a fix soon.
