### ISSUE TITLE
[Bug] `eksctl upgrade nodegroup` panics if a nodegroup is in a degraded state

### ISSUE THREAD

**Issue by cPu1** [weaveworks/eksctl#5487]
> 
> I received this error today after a fresh install of v0.104.0
> 
> ```
> j@jvm$ eksctl version
> 0.104.0-dev+6f5ce912.2022-06-24T12:46:32Z
> j@jvm:$ eksctl upgrade nodegroup --name=hardening-test --cluster=dev --launch-template-version 5
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x3a771ab]
> 
> goroutine 1 [running]:
> github.com/weaveworks/eksctl/pkg/actions/nodegroup.(*Manager).upgradeUsingAPI(0xc000119860, {0x53d6c28, 0xc0000720d0}, {{0x7fffc078d1b1, 0xe}, {0x0, 0x0}, {0x7fffc078d1e8, 0x1}, 0x0, ...}, ...)
> 	/tmp/eksctl-20220624-3451-qe9yyf/pkg/actions/nodegroup/upgrade.go:115 +0x2cb
> github.com/weaveworks/eksctl/pkg/actions/nodegroup.(*Manager).Upgrade(0xc000119860, {0x53d6c28, 0xc0000720d0}, {{0x7fffc078d1b1, 0xe}, {0x0, 0x0}, {0x7fffc078d1e8, 0x1}, 0x0, ...})
> 	/tmp/eksctl-20220624-3451-qe9yyf/pkg/actions/nodegroup/upgrade.go:84 +0x333
> github.com/weaveworks/eksctl/pkg/ctl/upgrade.upgradeNodeGroup(0xc000cefc98?, {{0x7fffc078d1b1, 0xe}, {0x0, 0x0}, {0x7fffc078d1e8, 0x1}, 0x0, {0x0, 0x0}, ...})
> 	/tmp/eksctl-20220624-3451-qe9yyf/pkg/ctl/upgrade/nodegroup.go:84 +0x347
> github.com/weaveworks/eksctl/pkg/ctl/upgrade.upgradeNodeGroupCmd.func1(0xc000341900?, {0xc000c1ab00?, 0x4?, 0x4?})
> 	/tmp/eksctl-20220624-3451-qe9yyf/pkg/ctl/upgrade/nodegroup.go:28 +0x9b
> github.com/spf13/cobra.(*Command).execute(0xc000341900, {0xc000c1aac0, 0x4, 0x4})
> 	/github/home/.cache/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
> github.com/spf13/cobra.(*Command).ExecuteC(0xc00066d900)
> 	/github/home/.cache/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
> github.com/spf13/cobra.(*Command).Execute(...)
> 	/github/home/.cache/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
> main.main()
> 	/tmp/eksctl-20220624-3451-qe9yyf/cmd/eksctl/main.go:102 +0x5db
> ```
> 
> Is there something I'm missing?
> 
> **edit:**
> 
> Seems this might be related to the fact the node group is not in an active state? Ironically I'm trying to update to a new launch template version to fix invalid user-data.
> 
> ```
> $ aws eks update-nodegroup-version --cluster-name dev --nodegroup-name hardening-test --launch-template name=hardening-test,version=5
> 
> An error occurred (ResourceInUseException) when calling the UpdateNodegroupVersion operation: Nodegroup cannot be updated as it is currently not in Active State
> ```

Originally posted in https://github.com/weaveworks/eksctl/issues/3102#issuecomment-1174683341.

**Comment by Himangini** [comment]
See comment [here](https://github.com/weaveworks/eksctl/issues/3102#issuecomment-1174706652)
