### ISSUE TITLE
[Bug] SharedConfigLoadError: failed to load config file

### ISSUE THREAD

**Issue by dienha93** [weaveworks/eksctl#5508]
### Version of AWS SDK for Go?
`1.44.35`

### Version of Go (go version)?
`go version go1.16.3 darwin/amd64`

### What issue did you see?
When I try to run the command `eksctl get clusters`. I get the error where it fails because it reads the ~/.aws/config but does not understand the `azure_default_password` property that configured for AWS login via Azure AD. And when I remove the profile config, it's work like a champ.

Error:
```
panic: SharedConfigLoadError: failed to load config file, /Users/myuser/.aws/config
caused by: INIParseError: invalid state with ASTKind { {4 NONE 0 [61]} true [{expr {1 STRING 0 [97 122 117 114 101 95 100 101 102 97 117 108 116 95 112 97 115 115 119 111 114 100]} true []}]} and TokenType comment

goroutine 1 [running]:
github.com/aws/aws-sdk-go/aws/session.Must(...)
	github.com/aws/aws-sdk-go@v1.44.35/aws/session/session.go:381
github.com/weaveworks/eksctl/pkg/eks.(*ClusterProvider).newSession(0xc000bbe750, 0xc0001647c8)
	github.com/weaveworks/eksctl/pkg/eks/api.go:514 +0x6e5
github.com/weaveworks/eksctl/pkg/eks.New({0x5fda660, 0xc0001a8010}, 0xc0001647c8, 0xc0003deb40)
	github.com/weaveworks/eksctl/pkg/eks/api.go:150 +0xda
github.com/weaveworks/eksctl/pkg/ctl/cmdutils.(*Cmd).NewCtl(0xc000164790)
	github.com/weaveworks/eksctl/pkg/ctl/cmdutils/cmd.go:63 +0x2dd
github.com/weaveworks/eksctl/pkg/ctl/get.doGetCluster(0xc000164790, 0xc000345698, 0x0)
	github.com/weaveworks/eksctl/pkg/ctl/get/cluster.go:63 +0xaa
github.com/weaveworks/eksctl/pkg/ctl/get.getClusterCmd.func1(0xc000e84500?, {0xc0006a3d30?, 0x1?, 0x1?})
	github.com/weaveworks/eksctl/pkg/ctl/get/cluster.go:37 +0x7b
github.com/spf13/cobra.(*Command).execute(0xc000e84500, {0xc0006a3d00, 0x1, 0x1})
	github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000158280)
	github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
	github.com/weaveworks/eksctl/cmd/eksctl/main.go:102 +0x5db
```

Here is my aws config: /Users/myuser/.aws/config
```
[profile tyme]
cli_pager=cat
region=eu-west-1
azure_tenant_id=my-tenent-id
azure_app_id_uri=my-app-id
azure_default_username=my-user-name
azure_default_password=my-password
azure_default_duration_hours=8
azure_default_remember_me=true
```

**Comment by Himangini** [comment]
Hello @dienha93 ,
This doesn't seem like `eksctl` issue to me. Any issues with parsing AWS configuration files, such as incorrect handling with certain options or hard-to-understand `INIParseError` errors, will need bug reports filed upstream in the [AWS Go SDK](https://github.com/aws/aws-sdk-go/issues). We heavily rely on AWS SDK to parse the config files.
