### ISSUE TITLE
[Bug] panic deleting a an already deleted cluster with the --force option

### ISSUE THREAD

**Issue by mnencia** [weaveworks/eksctl#5835]
### What were you trying to accomplish?

I'm writing code to clean up a cluster used in some automated tests.

### What happened?

```
$ eksctl delete cluster --disable-nodegroup-eviction --force --name eks-test
2022-10-26 16:05:01 [!]  failed to create provider for cluster; force = true skipping: unable to describe cluster control plane: operation error EKS: DescribeCluster, https response error StatusCode: 404, RequestID: bcd9d9bb-11ec-4897-80f7-f5a28ce40eee, ResourceNotFoundException: No cluster found for name: eks-test.
2022-10-26 16:05:02 [ℹ]  deleting EKS cluster "eks-test"
2022-10-26 16:05:07 [✔]  kubeconfig has been updated
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x499a55e]

goroutine 1 [running]:
github.com/weaveworks/eksctl/pkg/actions/cluster.(*OwnedCluster).Delete(0xc000e03540, {0x63d2608?, 0xc00012e008}, 0xc000c6c780?, 0x5a9cc20?, 0x0?, 0x1, 0xb8?, 0x5ba9290?)
	/private/tmp/eksctl-20221014-5242-mzrox6/pkg/actions/cluster/owned.go:118 +0x63e
github.com/weaveworks/eksctl/pkg/ctl/delete.doDeleteCluster(0xc00076aa50, 0x1, 0xfc?, 0x11b20c5?, 0xc000774100?)
	/private/tmp/eksctl-20221014-5242-mzrox6/pkg/ctl/delete/cluster.go:95 +0x2eb
github.com/weaveworks/eksctl/pkg/ctl/delete.deleteClusterCmd.func1(0xc00072d2c0?, 0x0?, 0x41?, 0xc000dbfcd8?, 0xc000dbfcd8?)
	/private/tmp/eksctl-20221014-5242-mzrox6/pkg/ctl/delete/cluster.go:20 +0x19
github.com/weaveworks/eksctl/pkg/ctl/delete.deleteClusterWithRunFunc.func1(0xc000aa4a00?, {0xc00072d2c0?, 0x5?, 0x5?})
	/private/tmp/eksctl-20221014-5242-mzrox6/pkg/ctl/delete/cluster.go:38 +0xc3
github.com/spf13/cobra.(*Command).execute(0xc000aa4a00, {0xc00072d270, 0x5, 0x5})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000732f00)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
	/private/tmp/eksctl-20221014-5242-mzrox6/cmd/eksctl/main.go:102 +0x5e5
```

### How to reproduce it?

Try deleting the cluster twice in a row. The second invocation will panic (CloudFormation stack in DELETE_IN_PROGRESS state). The same happens if you try to delete a cluster that has the CloudFormation stack in DELETE_FAILED state.

```
eksctl delete cluster --disable-nodegroup-eviction --force --name eks-test
eksctl delete cluster --disable-nodegroup-eviction --force --name eks-test
```

**Logs**

Logs from a try to delete a cluster with the CloudFormation stack in DELETE_FAILED state.

```
$ eksctl delete cluster --disable-nodegroup-eviction --wait --force -v 4 --name eks-test
2022-10-26 16:13:41 [▶]  role ARN for the current session is "arn:aws:iam::111111111111:user/redacted-user"
2022-10-26 16:13:42 [!]  failed to create provider for cluster; force = true skipping: unable to describe cluster control plane: operation error EKS: DescribeCluster, https response error StatusCode: 404, RequestID: 56759ce2-bb02-4b79-8c92-77f5a78e34b4, ResourceNotFoundException: No cluster found for name: eks-test.
2022-10-26 16:13:43 [▶]  role ARN for the current session is "arn:aws:iam::111111111111:user/redacted-user"
2022-10-26 16:13:43 [ℹ]  deleting EKS cluster "eks-test"
2022-10-26 16:13:43 [▶]  cfg.json = \
{
    "kind": "ClusterConfig",
    "apiVersion": "eksctl.io/v1alpha5",
    "metadata": {
        "name": "eks-test",
        "region": "eu-central-1",
        "version": "1.23"
    },
    "kubernetesNetworkConfig": {
        "ipFamily": "IPv4"
    },
    "iam": {
        "withOIDC": false,
        "vpcResourceControllerPolicy": true
    },
    "vpc": {
        "cidr": "192.168.0.0/16",
        "manageSharedNodeSecurityGroupRules": true,
        "autoAllocateIPv6": false,
        "nat": {
            "gateway": "Single"
        }
    },
    "privateCluster": {
        "enabled": false,
        "skipEndpointCreation": false
    },
    "cloudWatch": {
        "clusterLogging": {}
    }
}

2022-10-26 16:13:46 [▶]  cluster "eks-test" was created by eksctl
2022-10-26 16:13:46 [▶]  failed to check if cluster is operable: cluster info not available
2022-10-26 16:13:46 [!]  stack's status of nodegroup named eksctl-eks-test-cluster is DELETE_FAILED
2022-10-26 16:13:46 [▶]  nodegroups = []
2022-10-26 16:13:47 [▶]  reset current-context in kubeconfig to ""
2022-10-26 16:13:47 [✔]  kubeconfig has been updated
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x499a55e]

goroutine 1 [running]:
github.com/weaveworks/eksctl/pkg/actions/cluster.(*OwnedCluster).Delete(0xc000a66880, {0x63d2608?, 0xc000130008}, 0xc000823410?, 0x5a9cc20?, 0x40?, 0x1, 0x74?, 0x5ba9290?)
	/private/tmp/eksctl-20221014-5242-mzrox6/pkg/actions/cluster/owned.go:118 +0x63e
github.com/weaveworks/eksctl/pkg/ctl/delete.doDeleteCluster(0xc000c93130, 0x1, 0x7c?, 0x11b20c5?, 0xc0008c3e00?)
	/private/tmp/eksctl-20221014-5242-mzrox6/pkg/ctl/delete/cluster.go:95 +0x2eb
github.com/weaveworks/eksctl/pkg/ctl/delete.deleteClusterCmd.func1(0xc0007500e0?, 0x0?, 0x3e?, 0xc000d47cd8?, 0xc000d47cd8?)
	/private/tmp/eksctl-20221014-5242-mzrox6/pkg/ctl/delete/cluster.go:20 +0x19
github.com/weaveworks/eksctl/pkg/ctl/delete.deleteClusterWithRunFunc.func1(0xc0008ad400?, {0xc0007500e0?, 0x7?, 0x7?})
	/private/tmp/eksctl-20221014-5242-mzrox6/pkg/ctl/delete/cluster.go:38 +0xc3
github.com/spf13/cobra.(*Command).execute(0xc0008ad400, {0xc000750070, 0x7, 0x7})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000c84280)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
	/private/tmp/eksctl-20221014-5242-mzrox6/cmd/eksctl/main.go:102 +0x5e5
```

**Anything else we need to know?**

I'm using eksctl installed via brew on macOS 12.6, but the same error happens on linux when the cleanup runs in a GitHub Action.

**Versions**
```
$ eksctl info
eksctl version: 0.115.0-dev+2e9feac31.2022-10-14T13:01:18Z
kubectl version: v1.25.2
OS: darwin
```

**Comment by TiberiuGC** [comment]
Hey @mnencia - could you please help me with some details related to your automated tests. Specifically, I was wondering what configuration and operations do you apply to your cluster. How did you get the stack in `DELETE_FAILED` state in the first place?

**Comment by mnencia** [comment]
The DELETE_FAILED state is reached when I delete an EKS cluster where the AWS Firewall Manager created a security group in the cluster VPC. However, this is a known issue, and I'm handling that with my company's IT department.

It also happens when the stack is there states like "DELETE_IN_PROGRESS", "ROLLBACK_FAILED", and "ROLLBACK_COMPLETE" (we reach those states when we hit some rate limit during the creation of the cluster).

**Comment by mnencia** [comment]
Can you please reopen it? This is still valid.
