### ISSUE TITLE
Delete legacy cluster panics

### ISSUE THREAD

**Issue by martina-if** [weaveworks/eksctl#663]
**What happened?**

When I tried deleting an old cluster, I got a panic error stating that the nodegroup didn't exist. See details below.

**What you expected to happen?**
That the cluster is deleted without errors.

**How to reproduce it?**
I think this is reproducible only in old clusters.

**Anything else we need to know?**
What OS are you using, are you using a downloaded binary or did you compile eksctl, what type of AWS credentials are you using (i.e. default/named profile, MFA) - please don't include actual credentials though!

**Versions**
```
$ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.1.23"

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.8-eks-7c34c0", GitCommit:"7c34c0d2f2d0f11f397d55a46945193a0e22d8f3", GitTreeState:"clean", BuildDate:"2019-03-01T22:49:39Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

$ uname -a
Linux wanderer 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
Also include your version of `heptio-authenticator-aws`

**Logs**

```$ eksctl delete cluster --region us-west-2 attractive-wardrobe-1536157191
[ℹ]  deleting EKS cluster "attractive-wardrobe-1536157191"
[ℹ]  1 error(s) occurred while deleting nodegroup(s)
[✖]  not able to get stack "eksctl-attractive-wardrobe-1536157191-nodegroup-legacy-default" for deletion: describing CloudFormation stack "eksctl-attractive-wardrobe-1536157191-nodegroup-legacy-default": ValidationError: Stack with id eksctl-attractive-wardrobe-1536157191-nodegroup-legacy-default does not exist
	status code: 400, request id: 15e4f219-4f0f-11e9-9906-57732c6fb4d5
[ℹ]  will retry deleting nodegroup
[ℹ]  trying to cleanup dangling network interfaces
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x130581f]

goroutine 1 [running]:
github.com/weaveworks/eksctl/pkg/vpc.UseFromCluster(0x29d57e0, 0xc000745e60, 0x0, 0xc000468400, 0xc00000c018, 0x177)
	/go/src/github.com/weaveworks/eksctl/pkg/vpc/vpc.go:123 +0x41f
github.com/weaveworks/eksctl/pkg/eks.(*ClusterProvider).GetClusterVPC(0xc000758c00, 0xc000468400, 0x0, 0x0)
	/go/src/github.com/weaveworks/eksctl/pkg/eks/eks.go:107 +0x98
github.com/weaveworks/eksctl/pkg/ctl/delete.doDeleteCluster(0xc00007db80, 0xc000468400, 0x7ffcb8db4174, 0x1e, 0xc0007c0c80, 0x4, 0x26c32ac)
	/go/src/github.com/weaveworks/eksctl/pkg/ctl/delete/cluster.go:150 +0x7cd
github.com/weaveworks/eksctl/pkg/ctl/delete.deleteClusterCmd.func1(0xc0007c0c80, 0xc0006ad710, 0x1, 0x3)
	/go/src/github.com/weaveworks/eksctl/pkg/ctl/delete/cluster.go:33 +0x94
github.com/weaveworks/eksctl/vendor/github.com/spf13/cobra.(*Command).execute(0xc0007c0c80, 0xc0006ad680, 0x3, 0x3, 0xc0007c0c80, 0xc0006ad680)
	/go/src/github.com/weaveworks/eksctl/vendor/github.com/spf13/cobra/command.go:766 +0x2cc
github.com/weaveworks/eksctl/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x4596e20, 0x1, 0x5b, 0x2b)
	/go/src/github.com/weaveworks/eksctl/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/weaveworks/eksctl/vendor/github.com/spf13/cobra.(*Command).Execute(0x4596e20, 0x0, 0xc0001063a0)
	/go/src/github.com/weaveworks/eksctl/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
	/go/src/github.com/weaveworks/eksctl/cmd/eksctl/main.go:65 +0x2d
```

Here is the stack description: https://gist.github.com/martina-if/41b99aa37f586f8dae945e24cc6f29d9

**Comment by martina-if** [comment]
Closing because I think this is not an issue anymore.
